### ISSUE TITLE
autocommit cannot be enabled from prefs file  (3.0.86 candidate)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#620] opened 2019-11-06 19:36 UTC
If I have autocommit set in the preferences file, when I login, autocommit is not enabled.

![image](https://user-images.githubusercontent.com/13142166/68331308-a19a8780-0089-11ea-8d54-4f2b7cda85a1.png)

![image](https://user-images.githubusercontent.com/13142166/68331324-acedb300-0089-11ea-9d3a-4bc92302a486.png)

**Comment by ericwinger** [comment] 2019-11-06 22:00
If what I'm seeing is similar, you'll notice that autocommit is actually turned on when you open a browser. From then on, the transcript indicator is set properly. 

I think the problem is just with the indicator on login.  If you believe it's more serious let me know

**Comment by ericwinger** [comment] 2019-11-18 21:34
As suspected, autocommit was getting enabled but the indicator in the transcript wasn't set soon enough. Fixed in 3.0.88.

**Closed as completed by ericwinger** 2019-11-18 21:34 UTC
Labels: bug
