### ISSUE TITLE
Test status icons retained on focus change (3.0.93-8)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#736] opened 2020-02-27 19:18 UTC
If you run some tests in the SUnit browser, the test result icons used to stick around when you went to other classes and clicked back on that class, and update the Project Browser.  Now, the icons turn back into untested icons every time.

**Comment by LisaAlmarode** [comment] 2020-02-27 23:12
The issue appears to be in the project browser tab, not the sunit brower.  There is some disagreement about how things used to work and also how they should work; we don't seem to have any sort of specs for the ideal behavior.  Since this (I believe) changed behavior fixes issue #526, and Eric is making the project browser work consistently with the Sunit browser, closing this.  I will do more through testing in v8.  

If there are further complaints about stickiness of test results, a new issue should be filed and we'll need to discuss the corner cases of ideal behavior in detail.

**Comment by LisaAlmarode** [comment] 2020-03-02 06:10
In 3.0.93 pre-release 8, this bug is fixed, which means, the bad behavior for inherited tests in the project browser was re-introduced and issue #526 is re-introduced.

Here is an example of the problem:

Setup three classes, LisaTest, LisaSubTestOne, and LisaSubTestTwo.
```
TestCase rwSubclass: 'LisaTest'

instance method:
test_zork
	self assert: self zork

class method:
isAbstract
	^true

LisaTest rwSubclass: 'LisaSubTestOne'

instance method:
zork
	^false

class method:
isAbstract
	^false

LisaTest rwSubclass: 'LisaSubTestTwo'

instance method:
zork
	^false

class method:
isAbstract
	^false
```
Now, go to the Sunit browser and go to LisaSubTestOne and run all. You see the test pass.
Click on LisaSubTestTwo and you will see the untested icon (an envelope is not a untested icon that makes much sense to me, but so it is) 

However, in the project browser:
Go to LisaSubTestOne, click on the SUnit tab, and run all.  Again, test passes with a happy green check.
Click on LisaSubTestTwo, bring up the Sunit tab.  The test is checked green!  Which is **wrong**.  If you now run all tests on LisaSubTestTwo, it brings up the yellow triangle. 

This is the behavior in many past releases that was unaccountably healed in pre-release 7.  So technically this isn't grounds to not release.  However, it's not the agreed-upon plan, either.

**Comment by ericwinger** [comment] 2020-03-02 17:57
@LisaAlmarode If this bug is fixed, let's close it and open a new issue clearly identifying the regression in #526. It's still unclear to me what you really want.

**Comment by LisaAlmarode** [comment] 2020-03-02 18:00
The sunit browser and project browser are not consistent, and I don't want to re-enter my nice example, so please run the example and make things consistent.  I prefer the Sunit behavior.

**Comment by ericwinger** [comment] 2020-03-02 22:52
There seems to be many issues in this bug report, none of which are spelled out clearly. And there were errors in the use case https://github.com/GemTalk/Jadeite/issues/736#issuecomment-593237340 - inst method `zork` was false in both classes.

Fixed what I think is the problem in prerelease9. Now switching classes in both the sunit browser & sunit tab does not retain the last test run state.

**Closed as completed by ericwinger** 2020-03-02 22:52 UTC
Labels: P3-Annoyance

**Comment by LisaAlmarode** [comment] 2020-03-03 20:08
I am seeing the status not sticking after changing to a sibling with inherited tests, so I am happy.  Behavior in Sunit browser and project browser close enough for me.

I am also seeing another change in the PB, that switching classes if you are on the sunit tab doesn't switch you to the class definition view, which is a very nice new feature.
