### ISSUE TITLE
(3.0.77) clear all breakpoints menu item would be useful

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#515] opened 2019-09-09 14:03 UTC
After a debugging session when I've set a bunch of breakpoints, I usually just want to clear them all ... it is tedious to have to visit each method and manually clear all of the breakpoints ...

**Comment by dalehenrich** [comment] 2019-09-09 17:05
... in the same vein, topaz has the ability to disable/enable breakpoints a ... and I would find that feature to be really useful right about now in Jadite:)

**Comment by ericwinger** [comment] 2019-09-10 21:12
I can see how the clear breakpoints menu I implemented recently could be misinterpreted. 

Reworked clear breakpoints in 3.0.78. When you Browse Breakpoints from the transcript window, there is an extra menu item in the Methods menu in the menu bar ``Clear All Breakpoints``. That will clear all breakpoints in the system. On the regular Method menu there is a menu option ``Clear Method Breakpoints`` which will only clear breakpoints in the selected methods.

**Comment by ericwinger** [comment] 2019-09-10 23:31
Implemented a toggle in the ``Transcript Jadeite`` menu to disable breakpoints. Fixed in 3.0.78

**Comment by LisaAlmarode** [comment] 2019-10-14 22:02
I can't find the Clear All Breakpoints menu in 3.0.79.

![image](https://user-images.githubusercontent.com/13142166/66785947-9346ba80-ee93-11e9-82e1-67870780e6fa.png)

**Comment by ericwinger** [comment] 2019-10-16 17:41
@LisaAlmarode  Looks like there is some timing behavior going on as I see the ``Clear All Breakpoints`` menu item. Can you help me narrow the reproduction case? 

![image](https://user-images.githubusercontent.com/36212516/66944122-703a1900-f001-11e9-98a2-24fdcdd200be.png)

**Comment by LisaAlmarode** [comment] 2019-10-16 17:57
If you open the breakpoint browser from the methods pane of the Project Browser, the menu item isn't there.

**Comment by ericwinger** [comment] 2019-10-16 22:07
Fixed in 3.0.80. Clear All available regardless of where ``Browse Breakpoints`` is opened.

**Closed as completed by ericwinger** 2019-10-16 22:07 UTC
Labels: enhancement
