### ISSUE TITLE
(3.1.0) hung find class window

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#801] opened 2020-05-01 18:15 UTC
The find class window's been in this state for several minutes (no entry in error log) ... ended up killing task (thank goodness for autocommit):
![image](https://user-images.githubusercontent.com/623951/80829781-9fc70200-8b9c-11ea-9415-13ccb67a7f75.png)
This is in an image running against 3.6.0 with the base packaged ... however, it is not the first time I've run `find class`

**Comment by dalehenrich** [comment] 2020-05-01 18:26
This bug seems to reproduce (at least at the moment) by doing a `find class` with the debugger open and a project list with several test projects present.
`find class` works with test projects present, but no debugger:
![image](https://user-images.githubusercontent.com/623951/80830448-d5201f80-8b9d-11ea-9721-fe14bb627968.png)
then image hangs, when `find class` attempted with debugger open:
![image](https://user-images.githubusercontent.com/623951/80830664-37792000-8b9e-11ea-8d51-54c05137659c.png)
In case it matters, the test I was running is `RwProjectDeleteToolTest>>testDeleteProjectWithExtensionMethods_345` and here's the Rowan commit details:
![image](https://user-images.githubusercontent.com/623951/80830823-86bf5080-8b9e-11ea-962b-643d65d2d3f6.png)

**Comment by dalehenrich** [comment] 2020-06-17 19:05
bumped to critical, because I just hit this problem again this morning and had to kill jadeite and lose working state (with autocommit no code was lost, just time getting back to where I was when the image froze

**Comment by ericwinger** [comment] 2020-08-07 16:39
Is it fair to assume that a debugger was open at the same time the error occurred? (As in the previous examples)

**Comment by dalehenrich** [comment] 2020-08-07 17:25
Yes. in the second image and comment in the bug report, I state `then image hangs, when find class attempted with debugger open` and the debugger is visible in the image ...

**Comment by ericwinger** [comment] 2020-08-07 19:18
I should have been more specific. I was referring to the [June 17th comment](https://github.com/GemTalk/Jadeite/issues/801#issuecomment-645565325) which didn't explicitly state a debugger was open. Presumably it was.  The images are from May 1st.

**Comment by dalehenrich** [comment] 2020-08-08 00:00
Yes, I would have opened a new bug or mentioned the variation ... I re-reported the instance because I wanted to keep the issue "warm"

**Comment by ericwinger** [comment] 2020-08-18 23:30
Naturally, this is proving devilishly difficult to reproduce. [Because the debugger mucks with the idle state in a way that was found to be inaccurate](https://github.com/GemTalk/Jadeite/issues/819#issuecomment-670775128), I suspect my changes in that area may have fixed this problem. But I don't have proof of that. 

It would be helpful if I could see all windows open in the image next time this occurs. In windows 10, you can click on the Dolphin icon at the bottom of the screen which will bring up thumbnail view's as is shown below. If that is possible to capture, it might reveal another clue to the mystery. 

![image](https://user-images.githubusercontent.com/36212516/90575118-91165200-e16f-11ea-9339-54cd7de316c2.png)

**Comment by dalehenrich** [comment] 2020-08-19 00:52
Of course it doesn't reproduce for me either - `1 foo` from console workspace ... in the snapshot above I can see a test browser (likely source of the debugger) a project browser and a workspace window and that's my standard complement of windows (of courxe there would be multiple tabs open in the project browser ... these days I'm doing limited debugger work in jadeite as I am debugging the slowfilein, fastrowan and fastseaside build steps which don't involve much Rowan work ...

**Comment by ericwinger** [comment] 2020-08-19 18:43
I can't quite tell from the issue report and comments ...
Did the Find Class dialog hang when it was opening?  Or did it hang after you've entered values and have pressed ok (or cancel)?

**Comment by ericwinger** [comment] 2020-09-23 17:04
Attaching some notes from August 19th. Might be leading down the wrong path, but also might be a good place to resume when I take up this bug again. Without a reproduction case, it's hard to know what is useful data. 

```
issue #801 - hung find window.  
Tried recreating by running the debugger and simultaneously trying to open find class dialog. 
Got a hung process. After interrupting it with Ctrl-F12 found ProcessorScheduler waiting on semaphore `pendingReturns`. 
Found another process that could have been interesting but Dolphin broke when building the debugger - localVariable count error'd. Still determined that that weird other process might have been closing debuggers in the test. Not sure if I can believe that, however. Image froze at this point. 


Possible timing bug.  Initial process oop of debugger got recycled. Not obviously reproducible. Very intermittent.
Scenario: 
⦁	Debug tests in sunit browser on failing tests.
⦁	Open debugger. 
⦁	In separate browser, run same test that fails. 
⦁	Get notifier, open debugger - Walkback - `aGsProcess dnu stackDepth`  process oop appears to have been recycled

8/13/20 - Found a case where, the process had been saved & released in 
SessionTemps current  at: #'jadeiteProcesses' 
properly, but the subsequent save in  
SessionTemps current at: #'rowanServicesWindowRegistry'
for the debugger window didn't seem to save the process. The process got gc'd and the process oop was unused. Why didn't it save the process?  Or, what released it? 
New code which was releasing the contents of the registered window handle key should not have been. 
```

**Comment by ericwinger** [comment] 2022-06-10 17:56
Closing as I don't think it's reproduced in a long, long time.  @dalehenrich can reopen if it recurs.

**Closed as completed by ericwinger** 2022-06-10 17:57 UTC
Labels: bug, P1-critical

**Comment by dalehenrich** [comment] 2022-06-10 19:04
I continue to have various hanging issues when the debugger is open for Oscar 3.1, however, I don't think I've seen the hanging issue with Oscar 3.2 ... I'm so used to having it happen that I may have ignored a 3.2 episode ... but it is fair to close this issue for 3.1 with a will not fix ...
