### ISSUE TITLE
have to reset method in order to disable a break point

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#226] opened 2018-10-08 20:15 UTC
Here's screenshot of a method with a breakpoint on the `close` method:
![image](https://user-images.githubusercontent.com/623951/46631297-dd1bf880-cafb-11e8-9d0c-55e1c6d9dab4.png)
but note the clear breakpoint menu item isn't preset ... after reselecting the method (and trying twice):
![image](https://user-images.githubusercontent.com/623951/46631385-12284b00-cafc-11e8-8f79-4cbeb6d28a23.png)

cannot really tell whether the re-select is needed, but multiple attempts at finding th magic spot failed and in exasperation I've tried reselecting method and have a bit more success ...

**Comment by LisaAlmarode** [comment] 2019-08-20 21:33
I believe I saw some related problems in 3.0.75 when I was examining breakpoints within blocks - going back to the browser I wasn't able to get the menu items back.

**Comment by ericwinger** [comment] 2019-08-26 20:56
@LisaAlmarode I've visited the "magic spot" issue before and while it's probably worth exploring, it is a rather difficult problem. Since this but was created, I've added a ``Clear All Breakpoints" menu option. If you have just a single breakpoint, it should be functionally equivalent. Does this suffice? 

![image](https://user-images.githubusercontent.com/36212516/63722999-45092980-c809-11e9-85cd-c2178278b2b8.png)

**Comment by LisaAlmarode** [comment] 2019-08-28 17:29
While the remove-all-breakpoints is helpful, it's not a fix, I'm afraid. And while you can remove breakpoints, you still can't see senders and implementors.

The breakdown of all functionality in method source is easy to reproduce. 

1. go to a test method (I picked Rowan | AST-Kernel_tests-core | RBGemStoneNumberParserTest | tests | testNumberParser, 

2. Add a  breakpoint.  I put it on the first readStream.

3.  Use the method pane pop-up menu to run tests on this method.  At the breakpoint, do a continue.  It will bring you to the Sunit pane.

4.  Select the Method Source pane.  See breakpoint.  The popup menu will NOT include senders, implementors, add or remove breakpoints ever at any point.

This does not occur if I go to the Sunit pane to run the tests.

**Comment by ericwinger** [comment] 2019-08-30 23:06
Was clearing the step points & break points at an inopportune time. Fix is in Rowan & Jadeite in 3.0.77. 

Given the nature of the fix, it might be a good idea to find & review other issues where the break point set/clear is disappearing. I suspect some of these might be cleared up as well.

**Closed as completed by ericwinger** 2019-08-30 23:06 UTC
Labels: P3-Annoyance

**Comment by LisaAlmarode** [comment] 2019-09-24 19:07
The specific problems with losing the breakpoints and senders/implementors after running in debugger is fixed.

While normally I would try to document all the places where these menu items go missing, given that so many of them are due to bad data from the server in this old server version, it's not really useful.
