### ISSUE TITLE
(3.1.0) incorrect tab label in Project Browser

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#806] opened 2020-05-09 01:14 UTC
The selected tab, should probably be RwResolvedProject:
![image](https://user-images.githubusercontent.com/623951/81460035-9e2aaa80-9157-11ea-8d3c-bd29b253efc1.png)

**Comment by ericwinger** [comment] 2020-08-20 18:18
There's obviously a path through the code where the tab label does not get updated.  However, I don't have enough clues yet to track it down.  

If this happens again, please let me know what actions/clicks/etc you did immediately preceding the problem. Hopefully, that will give me enough to generate a reproduction case.

**Comment by dalehenrich** [comment] 2020-08-20 18:50
This happens pretty regularly with 3.1.0m but like most of the 3.1.0 bugs it is pretty random and I have not noticed any regular pattern ... it is worth noting the the actual bug seems to be that the tab **IS** updated, but it is using the wrong value ... as if a tab is updated with the previous tabs label ... just this morning I had a 4 tabs end up with the same (incorrect label) ... This morning I was definitely using the SUnit pane when this happened and definitely looking at test methods when this happened ... not that RwTestLibraryGenerator is in a package with tests although the class itself is not a test ...

**Comment by ericwinger** [comment] 2020-09-02 19:08
Using released Jadeite 3.1.0, I'm still unable to even see the problem. Code review doesn't reveal any leads. Assigning to Lisa in hopes she might find a reproduction case.

**Comment by LisaAlmarode** [comment] 2022-08-22 23:58
Jadeite 3.1.0 is Rowan v2, so this doesn't belong in the Rowan v3 project; and I don't reproduce it trivially in 3.2.9.  Moving it to the Jadite v3.1 project.

**Comment by LisaAlmarode** [comment] 2022-11-03 19:23
Two years old, on old version of Rowan, cannot reproduce; so closing; if anyone sees it in Rowan3 it should be reopened...

**Closed as completed by LisaAlmarode** 2022-11-03 19:23 UTC
Labels: bug
