### ISSUE TITLE
No Jadeite.errors produced

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#214] opened 2018-10-04 18:11 UTC
Need to investigate when & where a Jadeite.errors are produced in a runtime environment. Seem to missing stacks unexpectedly.

**Comment by dalehenrich** [comment] 2018-10-05 00:32
I just noticed that if I start Jadeite from a shortcut that is on `E:` a vmshare drive that is shared with the Linux disk, I **never** get an error file ... I just moved the jadeite directory to C: and voila an error file showed up ... so at least part of the problem is due to the use of vmshare ...

**Comment by dalehenrich** [comment] 2018-10-05 00:35
Nope that's not it either ... it's because I was expecting to actually see the ERROR extension for the error log file ... I don't use Windows enough to know that I need to read the fine grey print in the file browser to determine the type of the file ... silly me ...

**Comment by dalehenrich** [comment] 2018-10-05 00:40
... wait a second ... I deleted the error file in the directory on E:, then deleted the copy of the directory that I had made on C: ... then I did the operation that produced an error log file on the jadeite on E: and I'm not getting an error log file ... I guess I'm not blind after all ...

**Comment by ericwinger** [comment] 2018-10-09 19:09
I'd make sure you're running out of a local directory to eliminate problems with any vm share directories or other virualization problems. 

If you're still not seeing .errors files, there could be permission problems. I'd check that the directory with the .exe is writeable. 

Also, are you running the .exe with a shortcut? If so, look at the "Start in:" property. The logs could be going there. 

If there is still no file, you can look in the Windows Event Viewer under Windows Logs - Application. It's possible that there is more information available there. 

Other notes - 

- The error logs are written by the Dolphin VM. 
- It is possible to log an error directly from the Dolphin image with: ``SessionManager current logError: ex``  We might be able to rig up some test code in an .exe to experiment with that. 
- Information events can be sent as well. As an experiment, I sent ``SessionManager current logInformationEvent: 'FooFoo!'`` and it showed up in the Event Viewer. 
- We can also debug this together if you'd like.

**Comment by LisaAlmarode** [comment] 2022-11-08 22:05
This has not had complaints in some years, and it wasn't clear if this was a case of missing or misplaced logs; closing against more reliable information.

**Closed as completed by LisaAlmarode** 2022-11-08 22:05 UTC
Labels: bug
