### ISSUE TITLE
(3.0.64) category error

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#458] opened 2019-03-07 17:07 UTC
```
New Method: VMLibrary>>dump:path:stackDepth:walkbackDepth:
Message Selector: dump:path:stackDepth:walkbackDepth:

*----> Stack Back Trace <----*
{00920AE0: cf 00920AC1, sp 00920AF8, bp 00920ADC, ip 5, JadeSessionManager(SessionManager)>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a MessageNotUnderstood

{00920AC0: cf 00920A9D, sp 00920AD4, bp 00920AB8, ip 39, JadeSessionManager>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a MessageNotUnderstood
	stack temp[0]: '9:03:32 AM 3/7/2019'
	env temp[0]: a FileStream

{00920A9C: cf 00920A7D, sp 00920AB0, bp 00920A98, ip 3, JadeSessionManager(SessionManager)>>unhandledException:}
	receiver: a JadeSessionManager
	arg[0]: a MessageNotUnderstood

{00920A7C: cf 00920A5D, sp 00920A90, bp 00920A78, ip 3, JadeSessionManager(SessionManager)>>onUnhandledError:}
	receiver: a JadeSessionManager
	arg[0]: a MessageNotUnderstood

{00920A5C: cf 00920A41, sp 00920A70, bp 00920A5C, ip 5, MessageNotUnderstood(Error)>>defaultAction}
	receiver: a MessageNotUnderstood

{00920A40: cf 00920A0D, sp 00920A54, bp 00920A28, ip 55, MessageNotUnderstood(Exception)>>_propagateFrom:}
	receiver: a MessageNotUnderstood
	arg[0]: a ExceptionHandler
	stack temp[0]: nil
	stack temp[1]: a ExceptionHandler
	stack temp[2]: nil
	stack temp[3]: a Process('Main' base 00920000 [ACTIVE] in SessionManager>>logError: sp=00000000 ip=4 list=026A0010)
	stack temp[4]: nil

{00920A0C: cf 009209ED, sp 00920A20, bp 00920A08, ip 6, MessageNotUnderstood(Exception)>>_propagate}
	receiver: a MessageNotUnderstood
	stack temp[0]: nil

{009209EC: cf 009209D1, sp 00920A00, bp 009209EC, ip 13, MessageNotUnderstood(Exception)>>signal}
	receiver: a MessageNotUnderstood

{009209D0: cf 009209AD, sp 009209E4, bp 009209C8, ip 12, MessageNotUnderstood class>>receiver:message:}
	receiver: MessageNotUnderstood
	arg[0]: nil
	arg[1]: Message selector: select: arguments: #([] @ 14 in RowanClassService>>filterMethods: )

{009209AC: cf 0092098D, sp 009209C0, bp 009209A8, ip 4, Object>>doesNotUnderstand:}
	receiver: nil
	arg[0]: Message selector: select: arguments: #([] @ 14 in RowanClassService>>filterMethods: )

{0092098C: cf 00920969, sp 009209A0, bp 00920984, ip 21, RowanClassService>>filterMethods:}
	receiver: a RowanClassService
	arg[0]: a JadeiteProjectsBrowserPresenter
	stack temp[0]: nil

{00920968: cf 00920941, sp 0092097C, bp 0092095C, ip 14, RowanClassService>>computeVisibleMethods:browser:}
	receiver: a RowanClassService
	arg[0]: a ListPresenter
	arg[1]: a JadeiteProjectsBrowserPresenter
	stack temp[0]: nil

{00920940: cf 00920919, sp 00920954, bp 00920934, ip 4, RowanClassService>>displayMethodsOn:browser:}
	receiver: a RowanClassService
	arg[0]: a ListPresenter
	arg[1]: a JadeiteProjectsBrowserPresenter
	stack temp[0]: nil

{00920918: cf 009208F5, sp 0092092C, bp 00920910, ip 27, JadeiteProjectsBrowserPresenter>>refreshMethodsOn:}
	receiver: a JadeiteProjectsBrowserPresenter
	arg[0]: a ListPresenter
	stack temp[0]: a RowanClassService

{009208F4: cf 009208D1, sp 00920908, bp 009208EC, ip 13, EventMessageSend>>forwardTo:withArguments:}
	receiver: a EventMessageSend
	arg[0]: a JadeiteProjectsBrowserPresenter
	arg[1]: a Array

{009208D0: cf 009208B5, sp 009208E4, bp 009208D0, ip 5, EventMessageSend>>value}
	receiver: a EventMessageSend

{009208B4: cf 0092088D, sp 009208C8, bp 009208B0, ip 11, [] in MessageSequenceAbstract>>value}
	receiver: nil
	arg[0]: a EventMessageSend

{0092088C: cf 0092085D, sp 009208A8, bp 00920878, ip 30, EventMessageSequence>>messagesDo:}
	receiver: a EventMessageSequence
	arg[0]: [] @ 9 in MessageSequenceAbstract>>value
	stack temp[0]: a DeadObject
	stack temp[1]: 3
	stack temp[2]: a JadeiteProjectsBrowserPresenter
	stack temp[3]: a EventMessageSend

{0092085C: cf 00920841, sp 00920870, bp 0092085C, ip 15, EventMessageSequence(MessageSequenceAbstract)>>value}
	receiver: a EventMessageSequence
	env temp[0]: a ScintillaView

{00920840: cf 00920821, sp 00920854, bp 0092083C, ip 8, EventsCollection>>triggerEvent:}
	receiver: a EventsCollection
	arg[0]: selectionChanged

{00920820: cf 00920801, sp 00920834, bp 0092081C, ip 4, ListPresenter(Object)>>trigger:}
	receiver: a ListPresenter
	arg[0]: selectionChanged

{00920800: cf 009207E5, sp 00920814, bp 00920800, ip 4, ListView(ListControlView)>>onSelectionChanged}
	receiver: a ListView

{009207E4: cf 009207C9, sp 009207F8, bp 009207E4, ip 3, ListPresenter(SelectableItemsPresenter)>>onSelectionChanged}
	receiver: a ListPresenter

{009207C8: cf 009207A9, sp 009207DC, bp 009207C4, ip 6, ListView(ListControlView)>>onSelChanged:}
	receiver: a ListView
	arg[0]: a Array

{009207A8: cf 00920789, sp 009207BC, bp 009207A4, ip 7, ListView>>onSelChanged:}
	receiver: a ListView
	arg[0]: a Array

{00920788: cf 00920769, sp 0092079C, bp 00920784, ip 9, ListView(ListControlView)>>onSelChanged}
	receiver: a ListView
	stack temp[0]: a Array

{00920768: cf 00920745, sp 0092077C, bp 00920760, ip 22, ListView>>maybeSelChanging:}
	receiver: a ListView
	arg[0]: mouse
	stack temp[0]: a Array

{00920744: cf 00920725, sp 00920758, bp 00920740, ip 6, ListView>>nmClick:}
	receiver: a ListView
	arg[0]: a ExternalAddress

{00920724: cf 00920701, sp 00920738, bp 0092071C, ip 14, ListView(ControlView)>>nmNotify:}
	receiver: a ListView
	arg[0]: a ExternalAddress
	stack temp[0]: nmClick:

{00920700: cf 009206DD, sp 00920714, bp 009206F8, ip 31, ListView>>nmNotify:}
	receiver: a ListView
	arg[0]: a ExternalAddress
	stack temp[0]: -2

{009206DC: cf 009206AD, sp 009206F0, bp 009206C8, ip 18, CardContainer(View)>>wmNotify:wParam:lParam:}
	receiver: a CardContainer
	arg[0]: 78
	arg[1]: 4228
	arg[2]: 1701484
	stack temp[0]: a ExternalAddress
	stack temp[1]: a ListView

{009206AC: cf 0092067D, sp 009206C0, bp 00920698, ip 23, CardContainer(View)>>dispatchMessage:wParam:lParam:}
	receiver: a CardContainer
	arg[0]: 78
	arg[1]: 4228
	arg[2]: 1701484
	stack temp[0]: nil
	stack temp[1]: wmNotify:wParam:lParam:

{0092067C: cf 00920649, sp 00920690, bp 0092066C, ip 69, [] in InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: nil

{00920648: cf 00920621, sp 0092065C, bp 00920644, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 79 in InputState>>wndProc:message:wParam:lParam:cookie:

{00920620: cf 009205D5, sp 0092063C, bp 00920608, ip 84, InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: a InputState
	arg[0]: 66648
	arg[1]: 78
	arg[2]: 4228
	arg[3]: 1701484
	arg[4]: 850312
	stack temp[0]: a CardContainer

{009205D4: cf 009205AD, sp 00920600, bp 009205C8, ip 10, ListView(ControlView)>>defaultWindowProcessing:wParam:lParam:}
	receiver: a ListView
	arg[0]: 513
	arg[1]: 1
	arg[2]: 2293812

{009205AC: cf 00920591, sp 009205C0, bp 009205AC, ip 12, MouseEvent(WindowsEvent)>>defaultWindowProcessing}
	receiver: a MouseEvent

{00920590: cf 00920569, sp 009205A4, bp 00920584, ip 17, ListView>>onButtonPressed:}
	receiver: a ListView
	arg[0]: a MouseEvent
	stack temp[0]: a Array
	stack temp[1]: nil

{00920568: cf 00920549, sp 0092057C, bp 00920564, ip 8, ListView>>onLeftButtonPressed:}
	receiver: a ListView
	arg[0]: a MouseEvent

{00920548: cf 00920529, sp 0092055C, bp 00920544, ip 4, ListPresenter(Presenter)>>onLeftButtonPressed:}
	receiver: a ListPresenter
	arg[0]: a MouseEvent

{00920528: cf 00920501, sp 0092053C, bp 0092051C, ip 9, ListView(View)>>wmLButtonDown:wParam:lParam:}
	receiver: a ListView
	arg[0]: 513
	arg[1]: 1
	arg[2]: 2293812

{00920500: cf 009204D1, sp 00920514, bp 009204EC, ip 23, ListView(View)>>dispatchMessage:wParam:lParam:}
	receiver: a ListView
	arg[0]: 513
	arg[1]: 1
	arg[2]: 2293812
	stack temp[0]: nil
	stack temp[1]: wmLButtonDown:wParam:lParam:

{009204D0: cf 0092049D, sp 009204E4, bp 009204C0, ip 69, [] in InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: nil

{0092049C: cf 00920475, sp 009204B0, bp 00920498, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 79 in InputState>>wndProc:message:wParam:lParam:cookie:

{00920474: cf 00920435, sp 00920490, bp 0092045C, ip 84, InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: a InputState
	arg[0]: 66650
	arg[1]: 513
	arg[2]: 1
	arg[3]: 2293812
	arg[4]: 851240
	stack temp[0]: a ListView

{00920434: cf 00920415, sp 00920454, bp 00920430, ip 6, ShellView(View)>>isDialogMessage:}
	receiver: a ShellView
	arg[0]: a MSG

{00920414: cf 009203F5, sp 00920428, bp 00920410, ip 5, ShellView>>preTranslateMouseInput:}
	receiver: a ShellView
	arg[0]: a MSG

{009203F4: cf 009203D5, sp 00920408, bp 009203F0, ip 13, ShellView(View)>>preTranslateMessage:}
	receiver: a ShellView
	arg[0]: a MSG

{009203D4: cf 009203AD, sp 009203E8, bp 009203C8, ip 17, InputState>>preTranslateMessage:}
	receiver: a InputState
	arg[0]: a MSG
	stack temp[0]: 262956
	stack temp[1]: a ShellView

{009203AC: cf 0092038D, sp 009203C0, bp 009203A8, ip 19, InputState>>pumpMessage:}
	receiver: a InputState
	arg[0]: a MSG

{0092038C: cf 00920361, sp 009203A0, bp 0092037C, ip 18, InputState>>loopWhile:}
	receiver: a InputState
	arg[0]: [] @ 9 in InputState>>mainLoop
	stack temp[0]: a MSG
	stack temp[1]: true
	stack temp[2]: nil

{00920360: cf 00920345, sp 00920374, bp 00920360, ip 15, InputState>>mainLoop}
	receiver: a InputState

{00920344: cf 00920329, sp 00920358, bp 00920344, ip 14, [] in InputState>>forkMain}
	receiver: a InputState

{00920328: cf 0092030D, sp 0092033C, bp 00920328, ip 13, ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry}
	receiver: a ExceptionHandler

{0092030C: cf 009202E5, sp 00920320, bp 00920308, ip 22, [] in ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler

{009202E4: cf 009202C5, sp 009202F8, bp 009202E0, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:

{009202C4: cf 009202A1, sp 009202D8, bp 009202BC, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 17 in ExceptionHandlerAbstract>>try:
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:
	stack temp[0]: nil

{009202A0: cf 00920279, sp 009202B4, bp 00920294, ip 44, ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler
	arg[0]: [] @ 10 in InputState>>forkMain
	stack temp[0]: nil
	stack temp[1]: a Process('Main' base 00920000 [ACTIVE] in SessionManager>>logError: sp=00000000 ip=4 list=026A0010)
	env temp[0]: nil

{00920278: cf 00920255, sp 0092028C, bp 00920270, ip 7, BlockClosure>>on:do:}
	receiver: [] @ 10 in InputState>>forkMain
	arg[0]: ProcessTermination
	arg[1]: [] @ 13 in BlockClosure>>newProcess

{00920254: cf 00000001, sp 00920268, bp 00920254, ip 17, [] in BlockClosure>>newProcess}
	receiver: [] @ 10 in InputState>>forkMain

<Bottom of stack>

***** End of dump *****

***** Ending Dolphin stack dump started at 9:03:32 AM 3/7/2019 *****
```

**Comment by ericwinger** [comment] 2019-03-07 23:02
After failed compile, methods didn't get reinitialized. If you compiled successfully without changing methods or categories the problem was masked. Fixed in 3.0.65. https://github.com/GemTalk/Jadeite/commit/18a35c359ee30abc54060327fe34cce8b8586de5

**Closed as completed by ericwinger** 2019-03-07 23:02 UTC
Labels: bug

**Comment by dalehenrich** [comment] 2019-03-08 17:56
... verified that this bug is fixed

**Comment by LisaAlmarode** [comment] 2019-04-29 17:11
Since Dale didn't give the reproduction scenario, just take his assessment of fixed.
