### ISSUE TITLE
Abort of new method -> "String does not understand #format:"

### ISSUE THREAD

**Issue by martinmcclure** [ericwinger/Jade#580] opened 2019-10-17 22:30 UTC
Jadeite 3.0.80, Rowan sha b9fe7fcf.

In a browser, define a new method.
Leaving the new method selected, press the toolbar abort button/
Pop-up "String does not understand #format:"

**Comment by dalehenrich** [comment] 2019-10-17 23:08
Just an additional note that both Martin and I are working in candidateV2.0 (specifically issue_308) ... so [merge mistakes](https://github.com/GemTalk/Jadeite/issues/552#issuecomment-543338055) could be a root cause ... this particular case looks like a STON issue (IIRC #format: is sent in the case of a STON parsing error and this message is not present in Dolphin)

**Comment by ericwinger** [comment] 2019-10-18 23:04
Please let me know if this reproduces in 3.0.81 or later as I can't reproduce it. There was a missing method in my release. The issue described looks like it could have come from this area.

**Comment by LisaAlmarode** [comment] 2019-12-18 00:30
Closing, assuming it was something about the old version or a merge issue.

**Closed as completed by LisaAlmarode** 2019-12-18 00:30 UTC
Labels: bug
