### ISSUE TITLE
Loop-de-do when selecting classes in hierachy view, and variable scope pecularity

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#337] opened 2018-12-03 06:13 UTC
I have a set of classes that inherit, such that the hierarchy view looks like:
Object
    Vegetable
         Cabbage

When I have Vegetable selected, and click on Cabbage, it selects Cabbage, back to Vegetable, then back to Cabbage.

Also - not related, and possibly not a bug, but it was weird and confusing - when I have the Class bottom tab selected to look at the class methods, and I select the Variables tab, I get a long list inherited from Class, Metaclass3, Module and Behavior.  If my methods have class instance variables, they are included, but the list does not include class variables.  I understand technically why these are here.  But 19 is a lot of clutter, anything application-specific will get lost.

**Comment by ericwinger** [comment] 2018-12-05 19:00
@LisaAlmarode I can't reproduce the loop-de-do. Please check again in 3.0.52 when it's released as I did some work there. 

As far as displaying class instance variables from <meta> classes, I'm not sure that this should be changed. Dolphin displays them all and VisualWorks doesn't even bother. One possible enhancement that could help would be to italicize the variables that are defined in superclasses. This might be valuable on the instance side as well.  If that, or something similar, is valuable, please file a new issue.

**Comment by LisaAlmarode** [comment] 2018-12-10 19:24
No loop de loos in 3.0.52.  I will file a separate bug on vars.

**Closed as completed** 2018-12-13 18:22 UTC
