### ISSUE TITLE
(3.0.93 ... 3.1.0) Occasional freezes after "invalid session" error

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#746] opened 2020-03-12 16:46 UTC
If I've left my Jadeite session open overnight and I've suspended my laptop, I often get an 'invalid session" error, because the windows vm has timed out on the firewall connection (just guessing). Most of the time, when I get the "invalid session" error the whole session and all of the windows shut down ...
Occasionally, when I get a dialog about "saving a file" (I think), most of the windows are closed, but several of them remain and the process is unresponsive and I have to go to the task manager to terminate the process:
![image](https://user-images.githubusercontent.com/623951/76544426-41579000-6445-11ea-8863-90a9f853acb5.png)
This seems to be new behavior in 3.0.93, but I can't be certain. I've been getting "invalid session" errors for a couple of months now ...

When the "save dialog" pops up I can click on a button and the dialog goes away and if the process is going to freeze that's when it happens ... I would swear that there have been times when the dialog pops up and the process termnates cleanly, so it might be that the process hangs if a second dialog tries to pop up?

I don't think this is a high priority, especially since I'm not using th elatest version of dolphin, so I'm reporting this so that you are aware of a potential problem...

**Comment by dalehenrich** [comment] 2020-03-12 16:49
Another possibility is that the window with unsaved changes is the console window itself ... I don't often use the workspace in the console, but every once in a while i do ... in this case I can see that two workspace windows and a console are remaining and all or none of them could have been dirty...

**Comment by dalehenrich** [comment] 2020-03-13 16:17
DATAPOINT: I just had another "invalid session" event with an "unssved changes" dialog and I didn't save changes and the process terminated cleanly ...

**Comment by ericwinger** [comment] 2020-03-30 17:21
If you are able, try saving changes next time. If it hangs, it will give me a better chance at finding a reproduction case.

**Comment by dalehenrich** [comment] 2020-04-05 23:26
This time Jadeite froze with an invalid session error without any `save changes` dialog popping up ... something else must be going wrong...
![image](https://user-images.githubusercontent.com/623951/78512551-5e3c6600-775a-11ea-8c7c-faa2cecef9f3.png)
If you notice there is an unsaved workspace in the console, but the system froze before bring up any dialog ....

I had clicked on a method browser several times and didn't realize the the system was no longer connected to the server until I explicitly closed a window and boom ... invalid session ... several windows closed and then the system froze ...

**Comment by dalehenrich** [comment] 2020-04-08 00:01
I just had a case where running a 3.6.0 stone, I had the dialog pop up and I pressed yes and Jadeite exited without freezing ...

**Comment by dalehenrich** [comment] 2020-04-15 16:43
I just had a case where I had a freeze with no dialog popping up, but it looks like a popup should have happened as the console workspace has not been saved:
![image](https://user-images.githubusercontent.com/623951/79363783-350b9a80-7efd-11ea-89ab-2180bc7140da.png)
So this is a case where the image froze while bringing up the dialog?
There a number of windows that closed before hitting the dialog ... so perhaps once the closing sequence begins a dialog is bound to freeze the image?

**Comment by dalehenrich** [comment] 2020-04-29 01:05
This was a 3.1.0 freeze ... don't know whether or not the workspace window has been modified, but there was an open project browser, workspace, and test browser -- I got an invalid session notifier for this puppy:
console ![image](https://user-images.githubusercontent.com/623951/80552151-8f374180-897a-11ea-97e1-148e97e4c311.png)

**Comment by LisaAlmarode** [comment] 2022-11-17 20:21
Closing this since the dolphin upgrade changed the playing field.  There are still hangs in 3.2.12 (I get one sometimes on logout with unsaved changes), but this information is so old it's not really useful.

**Closed as completed by LisaAlmarode** 2022-11-17 20:21 UTC
Labels: bug
