### ISSUE TITLE
Walkback when attempting to copy text from a workspace

### ISSUE THREAD

**Issue by rjsargent** [ericwinger/Jade#960] opened 2022-11-04 19:39 UTC
I had a workspace with perhaps 60 lines of text that looked like Smalltalk.
e.g.
Float signBit: 1 rawExponent: 16r000 mantissa: 16r0000000000000	= -0.0
Float signBit: 1 rawExponent: 16r000 mantissa: 16r0000000000001	= -4.940656458412465e-324
... etc. 

When I attempted to copy the text so I could paste it into a document, I received a walkback:
a ImproperOperation occurred (error 2402), Cannot create a Symbol, String exceeds 1024 Characters. 'signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:mantissa:signBit:rawExponent:manti

Stack report:
[Jadeite_ImproperOperation_stack_report.log](https://github.com/GemTalk/Jadeite/files/9941490/Jadeite_ImproperOperation_stack_report.log)

Later, while trying to gather information about the walkback, I encountered a separate problem which prevented me from saving my workspace. I will create a separate issue for that.

**Comment by LisaAlmarode** [comment] 2022-11-09 20:59
The problem occurs when you attempt to open the menu, both the popup and the edit menu.  The problem is the keyword-colon pattern is assumed to be a selector, and it rolls on to compose a too-long selector.  It's quite hard to do this with a method text but quite easy with non-code.

this can be selected and popup menu works:
```
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 2
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 3
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 4
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 5
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 6
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 7
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 8
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 9
abcdefghij: 91 abcdefghij: 92 abcdefghij: 93
```

This, if selected, errors on popup.  The behavior is odd since you cannot press debug, focus is still on the workspace, but if I click on the windows task bar and touch another window, I can get focus on the walkback window and close it and continue. 
```
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 2
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 3
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 4
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 5
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 6
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 7
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 8
abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 1 abcdefghij: 9
abcdefghij: 91 abcdefghij: 92 abcdefghij: 93 abcdefghij: 94
```

**Comment by ericwinger** [comment] 2022-11-17 00:03
Was able to reproduce Lisa's reproduction case. There is some additional checking done on the server of the current selection in a workspace. This string is sent #asSymbol in some places but the max length of a symbol is 1024. If we encounter a string that is > 1024, we now avoid doing the extra checking.  Also found that the menu option browse implementors & senders were broken for a similar reason - and those menu items now get a warning message with explanation.

**Closed as completed by ericwinger** 2022-11-17 00:03 UTC
Labels: bug, P2-Significant, FixInFirstCut
