### ISSUE TITLE
[3.2.9] Concurrent debuggers can hang Jadeite

### ISSUE THREAD

**Issue by rjsargent** [ericwinger/Jade#927] opened 2022-08-12 19:33 UTC
Highlight an expression in the source pane, choose "Debug" from the pop up menu, nothing happens.
Evaluate something like "self halt printString" in the inspector text pane of the debugger and you can open a second debugger. However, closing the second debugger freezes Jadeite. UI is completely unresponsive with a spinner cursor.

It is _possible_ that the problem is caused by there being an error in the object's printString.

**Comment by rjsargent** [comment] 2022-08-12 19:43
SIGUSR1 stack report attached in gem log.
[gemnetobject27597galbadia.log](https://github.com/GemTalk/Jadeite/files/9329471/gemnetobject27597galbadia.log)

**Comment by LisaAlmarode** [comment] 2022-08-22 23:36
The second debugger scenario is quite bad.  If you execute self halt printString in the middle right pane of the debugger, various things may happen:
 - hard freeze
 - no immediate freeze, the selecting contexts in the debugger puts up an error dialog.
 - no immediate freeze, but going to the transcript in order to logout causes a freeze.

**Comment by ericwinger** [comment] 2022-10-04 23:29
I've reworked the debugger code in question to be much simpler and hopefully more robust. See checkins for details but, in short, we're using a `deferredValue` to do the asynchronous waiting instead of the poorly constructed forking code before. See JadeiteDebugger>>answer for the main changes. Closing for Lisa review.

**Comment by LisaAlmarode** [comment] 2022-10-06 16:11
The scenario in this bug results in a hard freeze in 3.2.11.  Easy to reproduce:
 - In transcript workspace, do a debug-it on something e.g. Array with: 1.
 - In the resulting debugger, execute-it on self halt printString.
 - Close second debugger using upper right window x.
 - See freeze... open taskmanager to kill jadeite.

**Comment by ericwinger** [comment] 2022-10-06 17:27
@LisaAlmarode I'm not able to reproduce in either a runtime or development environment. I have seen a freeze in a runtime environment but it didn't recur with this reproduction case. 
 Is this reliably reproducable?  Or is it intermittent? 
Also, is a Jadeite.errors produced?

**Comment by ericwinger** [comment] 2022-11-01 20:28
Lots of work on the debugger freezing Jadeite has been done including a complete rewrite of the debugger's waiting code which was the source of the problem. (Dolphin green threads are tricky) Lisa hasn't been able to reproduce it in 3.2.12 prereleases. I'm going to close this as fixed and we should create a new bug with a new reproduction case if it rears its ugly head again.

**Closed as completed by ericwinger** 2022-11-01 20:28 UTC
Labels: bug, P2-Significant, BlackDiamond, FixInFirstCut
