### ISSUE TITLE
`browse class` menu in method view of project browser leaves method and goes to class ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#243] opened 2018-10-18 16:06 UTC
... I would prefer that the currently selected method not be lost when using `browse class` ... i expected it to open a new tab or window, not leave the method I was in ..

**Comment by ericwinger** [comment] 2018-11-06 00:23
``Browse Class`` was renamed ``Find Class``. I left find class as is but added Go To Class in New Browser with a Ctrl-G to handle the request. (I use Find Class as is and expect it to search within my browser) 

Also replaced New Workspace Ctrl-N with New Project Browser Ctrl-N and renamed Add System browser with New Projects Tab Ctrl-N.  I think these are improvements.

**Comment by LisaAlmarode** [comment] 2018-11-13 23:42
The find class part is okay.

As far as I understand Eric's comments, it looks like control-N is not doing what it's supposed to be doing.  I think it's intended that control-N add a new tab in the projects browser.  Nothing happens for me.  

Also, the console workspace control-G behavior is muddled; it does a debugit per the menu bar, not find next per popup menu.  Should decide on what control-G really means and be a bit consistent.

Projects Browser
  control-N - does nothing
  shift-control-N - Project pane: does nothing.  method text pane: inserts red SO
  control-G - Project pane: does nothing.  method text pane: inserts red BEL
  shift-control-G (eventually) opens a find class dialog which opens a new PB
  control-F - Project pane: does nothing.  method text pane: Opens find text dialog.
  shift-control-F  opens a find class dialog which updates same PB

Console workspace
  control-N  - opens new workspace
  shift-control-N - causes red SO to appear in ws
  control-G  - does a debug it??  the popup menu claims that control-G does find next.  Menu bar Edit menu says that is F3.
  shift-control-G cause red BEL to appear in ws
  control-F  - opens text find dialog
  shift-control-F - opens a find class dialog which opens a PB

**Comment by ericwinger** [comment] 2018-11-14 00:39
> Projects Browser
control-N - does nothing

It works for me but it may depend on what you've got selected or on what tab you're on. Can you show me a screen shot of when it doesn't work? 

> shift-control-N - Project pane: does nothing. method text pane: inserts red SO

Any command key combination that isn't registered will give you cool red stuff. fyi 

>control-G - Project pane: does nothing. method text pane: inserts red BEL

I took away the Ctrl-G and returned Ctrl-B to be Debug in 3.0.47. 


> Console workspace
control-N - opens new workspace
shift-control-N - causes red SO to appear in ws
control-G - does a debug it?? the popup menu claims that control-G does find next. Menu bar Edit menu says that is F3.

Ditto.  I took away the Ctrl-G and returned Ctrl-B to be Debug in 3.0.47.

**Comment by ericwinger** [comment] 2018-11-15 00:00
@LisaAlmarode comment above.

**Comment by LisaAlmarode** [comment] 2018-11-15 01:36
> > Projects Browser
> control-N - does nothing
> It works for me but it may depend on what you've got selected or on what tab you're on. Can you 
> show me a screen shot of when it doesn't work? 

uh... it's the project browser.  With or without a project selected, package selected, class selected, method selected, focus in method text: control-N stubbornly ignores me.  I am native windows, though...

![image](https://user-images.githubusercontent.com/13142166/48523767-9b851880-e832-11e8-8206-3aa18e413ece.png)

- - -

Also, when I'm here, and I hit control-B (say, in trying to reach control-N), I get an error dialog:
RowanProjectService does not understand #replaceCrLfWithLf.  This varies depending on what I have selected in the list panes.  If I hit control-H, I get 
the error dialog ListView does not understand #findReplace.
The receiver varies per the pane I'm in and both work when I've got the text pane selected.

**Comment by ericwinger** [comment] 2018-11-15 17:39
Looks it wasn't just Ctrl-B & H. The other execution operation hot keys were problematic outside the source pane as well. Fixed in 3.0.48.

**Comment by ericwinger** [comment] 2018-11-15 17:54
Still can't reproduce the Ctrl-N problem. Putting back in @LisaAlmarode's court.

**Comment by ericwinger** [comment] 2018-11-15 19:07
The problem with Ctrl-N turns out to be a stripped method in the runtime executable. The image stripper removes unsent methods and isn't smart enough to decode the string-based menus used by Jadeite. (A hold over from Jade) Fixed in 3.0.48 by making a sender of ``newBrowser``.

**Closed as completed by ericwinger** 2018-11-15 19:07 UTC
Labels: enhancement
