### ISSUE TITLE
Need recursion protection ...

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#483] opened 2019-06-22 15:15 UTC
If the server goes into an infinite loop either via workspace or Rowan (my case:), there needs to be a way to terminate the process ... short of killing the gem, since killing the gem means that a developer will lose uncommitted work ...

**Comment by ericwinger** [comment] 2019-07-22 18:16
@dalehenrich There are two options that already exist: 

1. ``Console>Browse Processes`` allows you to debug or terminate server processes. (Right mouse ``Refresh`` may be needed) 
2. ``Ctrl-F12`` will interrupt the gci call in the Dolphin gui. 

Let me know if these aren't sufficient.

**Comment by LisaAlmarode** [comment] 2019-08-20 01:02
I created an infinite loop in server code, and neither of these techniques helps.  User interrupts show a dialog but don't effect the looping; and I can't get the browse processes to open anything.  Appears totally wedged.

**Comment by LisaAlmarode** [comment] 2019-08-20 01:07
The good news is that it actually did eventually put up an almost out of stack exception, which I closed, and no work was lost.  But "wait it out" might not be a preferred workaround.

**Comment by ericwinger** [comment] 2019-08-27 16:59
@LisaAlmarode  Can you share the infinite loop code so I can reproduce your scenario? 

Also, after you did a Ctrl-12 user interrupt to get control back, did you try using ``Soft Break`` or ``Hard Break`` on the ``My Session`` tab on the transcript?

**Comment by LisaAlmarode** [comment] 2019-08-28 17:46
```
loopEndlessly
	System _sleepMs: 100.
	self loopEndlessly.
```

It hangs again if I try to change focus to the my session tab.  So I tried controlF12 again.  And  I did manage to escape.  This is when executing the above code from the console workspace.

(1) control F12.
(2) close error dialog
(3) click on my session tab
(4) another control F12
(5) close error dialog
(6) press softbreak.  Nothing happens.
(7) bring up a popup-menu on the method pane of a method list browser. Now you see walkback with the softbreak.  
(8) At this point, the mouse cursor has gone missing anywhere over Jadeite. But if I change focus to another application I get the mouse back, so there's one extra step.

**Comment by ericwinger** [comment] 2019-08-30 20:30
In order to fix this issue, needed to override base method ``ProcessorScheduler>>userBreak:`` Dolphin (at least this version doesn't seem to have the concept of code overrides) throws a resumable error if you define a method in two packages. 

To get around this annoying problem, I created a new package ``Rowan UI Base PreInstall`` whose sole job for the moment is to remove the base version of ``userBreak:``before loading package ``Rowan UI Base``. This avoids the method conflict error. Note - doing it in the pre-install package script didn't work because the conflict error comes before the preinstall script runs which is rather silly. 

The fix for this problem involves sending a soft break to the session (if available) before the process is interrupted (usually with Ctrl-F12). Then after the User Interrupt message box is raised, we send a no-op server string execution to force the soft break error to be raised. 

Here is how it will look in 3.0.77 (screen shots from runtime image) 

![image](https://user-images.githubusercontent.com/36212516/64049539-ff5ea080-cb29-11e9-9233-2a3682ff6af2.png)

Press OK:
![image](https://user-images.githubusercontent.com/36212516/64049568-18ffe800-cb2a-11e9-9e70-a6894686e380.png)

Press Debug: 
![image](https://user-images.githubusercontent.com/36212516/64049599-30d76c00-cb2a-11e9-804b-1487614aa4b4.png)

**Closed as completed by ericwinger** 2019-08-30 20:30 UTC
Labels: enhancement
