### ISSUE TITLE
S-Unit Tests In an abstract class and its subclasses are not managed properly

### ISSUE THREAD

**Issue by regkrock** [ericwinger/Jade#336] opened 2018-12-02 15:35 UTC
When a TestCase is abstract, the tests should not appear in the S-Unit tab. And the subclasses of the the abstract class should show the tests which are inherited from the abstract testcase class.

Example:
![image](https://user-images.githubusercontent.com/7550442/49341593-90492f80-f61d-11e8-8e6b-8e6af5088200.png)

This is the subclass. Note the tests in the abstract super class are missing. They should be here.

![image](https://user-images.githubusercontent.com/7550442/49341610-f59d2080-f61d-11e8-9565-bcbcb23f7cc6.png)

**Comment by LisaAlmarode** [comment] 2018-12-05 19:03
An example in the current image is TonelAbstractWriterTest, which has a method testWriteSnapshot, and a subclass TonelCypressWriterTest that does not implement the method testWriteSnapshot, but inherits and expects to run that test.

On the SUnit tab, when TonelAbstractWriterTest class is selected, it shows the test testWriteSnapshot, which can be run but will fail.  As Reg notes, this should not be listed here.

On the SUnit tab, when the class TonelCypressWriterTest is selected, it correctly shows the test and runs successfully - that's all good.

In the SUnit browser, the problem is a bit worse.  The TonelAbstractWriterTest is included (which it should not be).  And it lists the method testWriteSnapshot which fails.

But it does NOT include TonelCypressWriterTest at all, so you cannot run the intended test at all from the SUnit browser.  I suspect that the SUnit browser just doesn't include inherited test methods.

FYI, Eric, TestCase implements isAbstract which can be overridden by subclasses that are abstract.

**Comment by ericwinger** [comment] 2018-12-12 00:06
Believe I have fixes for these in Oscar 3.0.53. Jadeite now properly uses TestCase protocol for determining which tests to show. e.g. considers ``isAbstract`` and friends now. but might need some additional work to solidify. @LisaAlmarode please open a new bug if needed. 

@LisaAlmarode - This test didn't show up because it's not in a Rowan package. 
> But it does NOT include TonelCypressWriterTest at all, so you cannot run the intended test at all from the SUnit browser. I suspect that the SUnit browser just doesn't include inherited test methods.

**Comment by LisaAlmarode** [comment] 2018-12-19 18:27
When you select the abstract test class, the class menu item "run tests" is enabled.  If you select that, it goes to the SUnit browser and says 0 run, 0 passed, etc.   Should disable this menu item.

**Comment by LisaAlmarode** [comment] 2018-12-19 18:32
Also, I'm assuming it's correct that tests in an abstract class are inherited by the immediate subclass, but not by subclasses of the immediate subclass.  tests that are in a concrete class are not inherited by any subclasses.  @regkrock might have an more knowledgeable opinion?

**Comment by dalehenrich** [comment] 2018-12-19 18:45
@LisaAlmarod, if you look at `TestCase class>>shouldInheritSelectors` you can see the logic that is used to determine which selectors are inherited from whom... a peek at the implementers of #shouldInheritSelectors will show that individual test cases can control their own destiny:)

**Comment by LisaAlmarode** [comment] 2018-12-20 02:47
Reassign to Eric to fix the PB class pane menu, the assumption that it's correct is correct...

**Comment by LisaAlmarode** [comment] 2018-12-20 21:42
Counterpropsal: replace the class menu "run tests" to "Open SUnit on class". Which will open an SUnit browser with the given class selected.  Remove the item "run tests"

**Comment by ericwinger** [comment] 2018-12-29 21:48
Fixed in Oscar 3.0.54. We can tweak the name of the menu item if need be.

**Closed as completed by ericwinger** 2018-12-29 21:48 UTC

**Comment by LisaAlmarode** [comment] 2019-01-10 01:01
Test Inheritance looks okay now including the inherit selectors behavior, at least per my limited understanding.
