### ISSUE TITLE
After removing class, don't collapse the hierarchy

### ISSUE THREAD

**Issue by ericwinger** [ericwinger/Jade#726] opened 2020-02-21 21:36 UTC
If you remove a class, it isn't helpful that the hierarchy collapses up to the parent class. Should show the hierarchy as it exists but without the removed class.

**Comment by LisaAlmarode** [comment] 2022-11-17 20:48
It behaves as the intended behavior as of v3.2.12, so this was fixed by some other work.

**Closed as completed by LisaAlmarode** 2022-11-17 20:48 UTC
Labels: P3-Annoyance
