### ISSUE TITLE
Oscar-3.0.40: Occasional `exactly one object must be selected` message when bringin up right button menu in method pane... when only one item selected

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#193] opened 2018-09-23 15:54 UTC
Note that I am in a Dictionary browser with one method selected and that there is a Project browser open that only has a project selected:

![image](https://user-images.githubusercontent.com/623951/45929937-4bae6300-bf0d-11e8-888b-c73f4edbd819.png)

selecting and deselecting does not seem to help ... in fact it seems that the bad state is produced when I open the browser from the inspector in a debugger (Issue #192) ....

**Comment by LisaAlmarode** [comment] 2018-10-10 21:02
I can reliably reproduce this in 3.0.41, when classes are in hierarchy view (open the dictionary browser from the console).  The popup works okay in the ordinary list classes view.

**Comment by ericwinger** [comment] 2018-10-26 22:29
@LisaAlmarode  Hmmm, I'm not having any luck reproducing this with the dictionary browser/hierarchy view in 3.0.43. Any guidance is appreciated. 

![image](https://user-images.githubusercontent.com/36212516/47595195-df6fb680-d933-11e8-984b-039faa5bbad1.png)

**Comment by dalehenrich** [comment] 2018-10-31 01:18
Try to copy the selected item (CTL-C) .. reproduces with 3.0.43:
![image](https://user-images.githubusercontent.com/623951/47760149-fd108900-dc6f-11e8-800a-b660a8a54be6.png)

**Comment by LisaAlmarode** [comment] 2018-10-31 17:02
@ericwinger it's the text pane popup, not the method list pane popup. Remains easy to reproduce, as Dale says, in 43.

**Comment by ericwinger** [comment] 2018-11-01 17:17
@LisaAlmarode  Still no luck reproducing. :(   I'm using Oscar 3.0.44. 

![image](https://user-images.githubusercontent.com/36212516/47867590-2f7ccc00-ddbf-11e8-8f8d-964eca53e51a.png)

**Comment by ericwinger** [comment] 2018-11-01 18:40
Got it. Missed the hierarchy note. Fixed in 3.0.45.

**Closed as completed by ericwinger** 2018-11-01 18:40 UTC

**Comment by LisaAlmarode** [comment] 2018-11-02 01:25
It no longer errors.  However, for a longish method it takes a long time to show the menu - close to 2 seconds - long enough for me to get bored and right-click again.  An example of this is TonelWriter>>splitMethodSource:into:. Under similar circumstances, the Project Browser pops it right up.  
However, since Dictionaries Browser is deprecated, I think we can let this pass.
