### ISSUE TITLE
(3.0.63) sticky package selection

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#450] opened 2019-02-22 19:27 UTC
Don't know exactly how got here (I had been doing some drag drop between classes in different packages via the class hierarchy --- drag from a subclass in one package into a superclass in another, but it was only after a bit of time went by to notice the permanent selection), but the package GsDevKit_upgradeDevKitImage-Core seems to be permanently selected no matter what I do:
![image](https://user-images.githubusercontent.com/623951/53265773-e44f3780-3693-11e9-8056-fc430b6347e3.png)
opening a new project browser does clear the selection

**Comment by ericwinger** [comment] 2019-02-25 20:50
When two packages are selected, we don't update the hierarchy. Since you're seeing a hierarchy I suspect that you've actually only got one package selected. The "permanent select" might be a Dolphin visual artifact from a selection that didn't get properly invalidated. 

I'd be curious of a few things if this happens again: 

- Does dragging another window over the "permanent selection" erase it wherever the window covers it? 
- Does selecting a new project clear the package list as it's supposed to?

Removing the February label assuming it's a gui artifact in Dolphin. Reassigning back to @dalehenrich for feedback if this happens again.

**Comment by dalehenrich** [comment] 2019-02-25 20:58
... FWIW, I believe that I tried "everything" in an attempt to avoid having to close the project browser

**Comment by LisaAlmarode** [comment] 2022-11-08 22:03
No reports of reproduction so I think we can blame it on dophin.

**Closed as completed by LisaAlmarode** 2022-11-08 22:03 UTC
Labels: bug
