### ISSUE TITLE
Debuggers (old and new) text panes get error on popup menu

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#68] opened 2018-08-19 00:57 UTC
As noted in #49... in both the new and old debuggers, when I execute String foo and open the debugger, the right-click popup menu gives me an error and then another error. This is 3.0.13 with rowan oscar b4503fc.

With enable checked: 
 ![image](https://user-images.githubusercontent.com/13142166/44304386-9ab21880-a30f-11e8-88a0-3dcbfa18d949.png)

![image](https://user-images.githubusercontent.com/13142166/44304389-a1409000-a30f-11e8-9b11-8f421405a383.png)

Without enable checked: 
![image](https://user-images.githubusercontent.com/13142166/44304393-bfa68b80-a30f-11e8-9bb4-8e0e7ad674c6.png)

**Comment by jgfoster** [comment] 2018-08-19 16:52
@LisaAlmarode,

Just to confirm, this happens for you with the following steps:

1. Launch Jadeite
2. Log in to a freshly created Rowanized repository
3. Enable the new debugger
4. In the Jadeite Transcript Workspace type 'String foo' (without the quotes)
5. With the cursor on that line, press <Ctrl>+<E> (for execute)
6. Observe the error: "Error while processing error"

Is that right? If so, then when you get the error message, try holding down the shift key when you press 'OK'. This might give us more information. If you are following other steps than the above, please describe them in more detail. Thanks!

**Comment by ericwinger** [comment] 2018-08-20 17:55
I can confirm that trying to open the context menu in the debugger source pane gives this dialog: 

![image](https://user-images.githubusercontent.com/36212516/44357694-897c1f80-a467-11e8-8174-eab03d4fc304.png)

**Comment by jgfoster** [comment] 2018-08-21 00:33
It took a few hours, but I've been able to reproduce the error in an automated test (RowanDebuggerTestCase>>testContextMenu will be committed in a few minutes). 

The walkback is in MethodSourcePresenter>>methodMenuBreak: which was introduced by  05345346949158f7663032c7a3b840f4d8b999d4. Since I don't understand what that code is intended to do, I'll let Eric investigate.

**Comment by ericwinger** [comment] 2018-08-21 17:03
I believe this is fixed as of Oscar 3.0.16

**Closed by ericwinger** 2018-08-21 17:03 UTC
Labels: bug, debugger
