### ISSUE TITLE
(3.0.66) silent commit conflict/failure when auto commit is enabled

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#462] opened 2019-04-24 18:49 UTC
I don't know for certain that this is the case, but I had been working for a few minutes in Jadeite with autocommit enabled, when I noticed that work I had done was not available to a session in topaz. I had been working pretty regularly making changes in Jadeite and then running a topaz script, and up until that moment, when I noticed the changes did not seem to be propogated, auto commit had been working fine ... the Jadeite session has been open for several days...

Anyway, I pressed the commit button on the project browser and got a commit failure dialog ... I saved my recent work (copied method), aborted, then recovered my changes and the system started working as expected again ...

It is not likely that the commit failure happened in the moments before I pressed the commit button, so I can only say that I am suspicious that I had been living for a few minutes with failing autocommits ...

My suspicion is based on the fact that I made a change in Jadeite and then pressed the commit button for good luck when I got the commit failure dialog ... the implication being that moments before the failure I should have triggered an autocommit ... anyway, it is a single user stone ...

**Comment by ericwinger** [comment] 2019-04-24 23:02
@dalehenrich It's a good theory. Any recommendations on how to code up a simple commit conflict in a single session so I can investigate?

**Comment by dalehenrich** [comment] 2019-04-24 23:20
Let's see ... add an association to UserGlobals commit ... in topaz session abort, in Jadeite turn on autocommit, abort.
In topaz add a new value to the association and commit ... in Jadeite in a workspace change the association (do not abort or commit) then edit a method and save ... you should get a commit conflict ... I'll be in office tomorrow if you need more help

**Comment by ericwinger** [comment] 2019-04-26 23:32
The first cut at a fix is complete. 
@dalehenrich Can you think of a way to create a commit failure using a single session? I'd like to write some automated tests but Jadeite doesn't support multiple sessions yet.

**Comment by dalehenrich** [comment] 2019-04-26 23:47
It takes two sessions to tango ... You should be able to use 
**GsExternalSession**:

     GsExternalSession newDefault
	login;
	executeString: '<modify-shared-global>';
	commit;
	logout

Ought to do the trick...

Dale

**Comment by ericwinger** [comment] 2019-05-02 21:29
Visual indication is a red auto commit button. Tests added and functionality seems to be working in 3.0.69. https://github.com/GemTalk/Jadeite/commit/827881dbce3f7bba2c91c6e5aa90dd429c19a7dc

**Comment by LisaAlmarode** [comment] 2019-09-23 22:01
There is no way I'd notice the background turning red on the autocommit icon... especially when testing from a workspace that obscured that part of the dialog.  It seems still silent.

Reopen and reassign to Dale since he would have an opinion on how this should be indicated...

**Comment by dalehenrich** [comment] 2019-09-23 23:24
I agree with @LisaAlmarode, we need something a bit more obvious ... at a minimum I think that a dialog should come up with the information that the autocommit feature had a commit failure. The user should be given the option of doing an abort (and immediately forgetting the last unit of work) or turning off autocommit and giving the user the option of recovering their work before doing an abort. Extra credit for giving the user an inspector on the System class>>transactionConflicts dictionary if they choose not to abort. Bounce back to @ericwinger.

**Comment by ericwinger** [comment] 2020-03-04 18:45
Now throw a dialog if the auto commit fails. Dialog will allow the user to abort or not. If they choose not to abort, an inspector on the transaction conflicts dictionary is opened. Fix in 3.1.0

**Closed as completed by ericwinger** 2020-03-04 18:45 UTC
Labels: bug

**Comment by LisaAlmarode** [comment] 2020-04-15 22:01
Dale's use case doesn't reproduce problems, presumably since ad-hoc execution is also committed by autocommit. So whatever tests you have, @ericwinger, are not testing anything... 

However, by setting up commit in  a hot loop in topaz I triggered an autocommit conflict (on an ad-hoc execution) and indeed icons turned red and dialogs came up.
