### ISSUE TITLE
(Oscar 3.0.73) `Find Class ...` menu item greyed out after opening new tab

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#490] opened 2019-07-23 14:04 UTC
Here's the evidence of the inactive menu item:
![image](https://user-images.githubusercontent.com/623951/61718065-0f0eec00-ad17-11e9-89de-7f8c076a65c0.png)
Of course when I attempted to produce more detailed pictures, the menu item refused to go inactive ... including after logout ...

**Comment by ericwinger** [comment] 2019-07-23 16:27
@dalehenrich The ``Find Class...`` menu option is disabled only while the browser tab is being opened. It is enabled in the method ``JadeiteProjectBrowserPresenter>>queryCommand:.`` There is no code path to disable it once enabled. Therefore, a problem might have occurred before the browser tab was fully built. Can you look in your Jadeite.errors file to see if there is any suspicious activity about the time of the problem? 

Also, if it happens again, can you attach a picture of the underlying tabs & toolbar? The menu is covering them. If the browser tab got in trouble, the tabs and toolbar might provide a clue.

**Comment by dalehenrich** [comment] 2019-07-23 16:45
Haha I was trying to get a picture of the tabs, when the problem went away ... no entry in the error log ... 
I just logged in, selected a project, opened a new tab and did `find class`...

Is there a way to move a menu around once it has been opened?

**Comment by dalehenrich** [comment] 2019-07-23 16:52
This is what the browser looked like before I attempted to do find class ...
![image](https://user-images.githubusercontent.com/623951/61730979-5acd8f80-ad2f-11e9-90ae-da120d58f28c.png)

**Comment by ericwinger** [comment] 2019-07-23 17:05
> Is there a way to move a menu around once it has been opened?
No way to move a menu once it's opened. (That I know of) 

I'm going to assign to Lisa to see if she can reproduce this as I'm not having any luck. My best guess is that the tab wasn't fully built before it allowed you to open the menu. Conceivably, there could be a window of time between the tab construction and the menu enablement when gui control is released to the user. A slow client (or a poorly timed mouse click) could allow enough time for this problem to manifest.

**Comment by LisaAlmarode** [comment] 2019-07-30 17:58
My particular slow client configuration doesn't have a gap; turns into a busy cursor right at the icon click, by the time I'm allowed to see a menu it's never grayed out. 

It might be a slowish GUI with a very fast backend? 

Eric, I'm reassigning to you since if it's a rare timing issue that only Dale sees, it might need some instrumentation.  Dale would have to decide the priority.

**Comment by ericwinger** [comment] 2019-07-31 22:03
@dalehenrich Neither Lisa nor I are able to reproduce this. Is this a common occurrence for you or a one-time event? What priority do you give to fixing this?

**Comment by dalehenrich** [comment] 2019-07-31 23:08
If you can't reproduce or see a path that would lead to the menu being disabled, then we'll just hope that you run into this in your development environment before anyone else runs into it:) ... or better yet, we never see it again, because it's been magically fixed:)

**Comment by ericwinger** [comment] 2019-07-31 23:13
Let's retire it then. If you see it again and can gather any more information, please reopen this issue.

**Closed as completed by ericwinger** 2019-07-31 23:13 UTC
Labels: bug
