### ISSUE TITLE
[3.2.9] Seeing "SmallInteger does not understan #wait" when dragging a method

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#931] opened 2022-08-22 22:21 UTC
I have been sporadically seeing this error.  It appears to be when I decide to drag a method to another place and my mouse hesitates as I trying to decide where I'm going to; specifically, if my hesitation leaves the mouse point on the narrow gray bar between the panes, not a pane itself.  I can reproduce it reliably, by dragging a method very slowly horizontally from right to left.  

[Jadeite.txt](https://github.com/GemTalk/Jadeite/files/9397908/Jadeite.txt)

**Comment by ericwinger** [comment] 2022-08-25 18:09
Looks like a drag drop failure which only reproduces in the runtime executable is caused by an incorrect return value in Dolphin base code. 

Instead of returning a duration, DragDropSession>>defaultScrollInterval returns an integer. #wait sent to the Integer gets an MNU.

I was able to reproduce in the released 3.2.9 runtime executable.  After cutting a new executable with the fix, the bug did not reproduce for me.

**Comment by ericwinger** [comment] 2022-08-25 18:09
Fix will be in Jadeite 3.2.10

**Comment by LisaAlmarode** [comment] 2022-08-30 20:02
The core bug is fixed.  However, when testing I noticed the drag icon is an email symbol... this ought to be fixed as I was taken aback.  
![image](https://user-images.githubusercontent.com/13142166/187531757-64253a03-e1d2-4e26-bd98-55ffc96067eb.png)

**Comment by ericwinger** [comment] 2022-09-29 22:22
When Dolphin drags an object, it asks the object for it's icon. In the case a method drag, the underlying object is a method service. The icon I selected for that was a "message" icon.  Can you suggest something better?

**Comment by LisaAlmarode** [comment] 2022-11-02 18:25
Hmm. From a user's point of view, a method is not a message. 
Dragging a class give a capital 'U' which is not confusing, exactly, but quite baffling. 
Text drag gives a little box which is okay.

What are the options for different icons, can you provide some alternatives?  Keeping it simple is best. While the little box is not entirely ideal, it would be better than the envelope or U.

**Comment by ericwinger** [comment] 2022-11-03 19:28
Changed the icon to a gearwheel for both method and class drags based on Lisa's suggestion.

**Closed as completed by ericwinger** 2022-11-03 19:28 UTC
Labels: FixInFirstCut, AdditionalTweaking
