### ISSUE TITLE
(3.0.50) pass/fail icons associated with test in sunit browser not stable

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#294] opened 2018-11-17 19:43 UTC
Here's a picture of fresh `run all`:
![image](https://user-images.githubusercontent.com/623951/48665073-46791a80-ea5d-11e8-8dbb-e3a675231892.png)
then select a different method in project browser, come back to sunit browser and run your mouse over the test results ... voila some of the test results are magically lost:
![image](https://user-images.githubusercontent.com/623951/48665100-bd161800-ea5d-11e8-90a3-28a70efe0a84.png)

**Comment by dalehenrich** [comment] 2018-11-17 19:44
oh look! non-test methods are being included in the list as well!

**Comment by dalehenrich** [comment] 2018-11-17 19:47
The extra methods (setup, etc.) show up in the sunit browser after changing a method in the test class ... 

It seems that the test status is scrambled when any method is changed (or selected?) in the project browser

**Comment by dalehenrich** [comment] 2019-01-02 19:24
(3.0.53) ... this behavior is still present ... at the moment though, the change from listing just test methods to listing all methods in class seems to be triggered when the commit button is pressed ...

**Comment by dalehenrich** [comment] 2019-01-07 20:03
@ericwinger I told you this morning that occasionally non-test methods show up in the SUnit browser .. here's a picture:
![image](https://user-images.githubusercontent.com/623951/50790517-f9067600-1273-11e9-9a3e-35d99336020c.png)
All tests in a single class ... we tried a simple commit, but something may have to change .... I was working (as usual) and didn't notice that the extra methods appeared until I had done several operations including writing out changes; viewing changes; running tests; removing (non-test) methods; committing, etc.

**Comment by dalehenrich** [comment] 2019-01-07 20:30
It looks like the SUNIT browser method list *corruption* is occurring after a **load** of a new version of Rowan --- that **does not** have any changes to the `RwRowanSample7Test` class

**Comment by dalehenrich** [comment] 2019-01-07 21:04
empty changes before load:
![image](https://user-images.githubusercontent.com/623951/50793260-72a26200-127c-11e9-9a00-bd0477929eaf.png)
window state immediately after load of all projects (note the extra methods that appear in SUnit browser):
![image](https://user-images.githubusercontent.com/623951/50793294-94034e00-127c-11e9-9e5f-d9cf38546a09.png)

**Comment by LisaAlmarode** [comment] 2019-01-17 06:23
The title of this bug refers to a problem that still exists in 3.0.56, and is annoying. 

The bulk of the verbiage (picturiage?) is about a separate issue of non-test methods popping up in the sunit browser.  This was reported recently as #395 and does not reproduce in 3.0.56.  I also cannot reproduce a non-test-method-appearance problem when a package is loaded.

So I'm thinking that part is fixed and filed a separate bug for the icons issue and closing this one.

**Closed as completed by LisaAlmarode** 2019-01-17 06:23 UTC
Labels: bug, P1-critical
