### ISSUE TITLE
(3.0.52) error using debugger: `Index 5 is out of bounds`

### ISSUE THREAD

**Issue by dalehenrich** [ericwinger/Jade#362] opened 2018-12-15 00:49 UTC
I can click around on other frames in the debugger, but every time I hit the selected frame I get this error popup:
![image](https://user-images.githubusercontent.com/623951/50036721-de681680-ffbf-11e8-803a-634d351f0be5.png)

Here's the dolphin error stack:
```
***** Starting Dolphin stack dump at 4:43:28 PM 12/14/2018 *****

************************** Dolphin Virtual Machine Dump Report ***************************

16:43:28 PM, 12/14/2018: Index 5 is out of bounds

*----> VM Context <----*
Process: {1DAD0210:size 556 words, suspended frame 1DAD0F69, priority 5, callbacks 2
last failure 2:nil, FP control 80017, thread 00000000}
Active Method: SessionManager>>logError:
IP: 007EE629 (9)
SP: 1DAD0BC4
BP: 1DAD0B98 (595)
ActiveFrame: {1DAD0B9C: cf 1DAD0B7D, sp 1DAD0BB4, bp 1DAD0B98, ip 5, JadeSessionManager(SessionManager)>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a BoundsError


New Method: VMLibrary>>dump:path:stackDepth:walkbackDepth:
Message Selector: dump:path:stackDepth:walkbackDepth:

*----> Stack Back Trace <----*
{1DAD0B9C: cf 1DAD0B7D, sp 1DAD0BB4, bp 1DAD0B98, ip 5, JadeSessionManager(SessionManager)>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a BoundsError

{1DAD0B7C: cf 1DAD0B59, sp 1DAD0B90, bp 1DAD0B74, ip 39, JadeSessionManager>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a BoundsError
	stack temp[0]: '4:43:28 PM 12/14/2018'
	env temp[0]: a FileStream

{1DAD0B58: cf 1DAD0B39, sp 1DAD0B6C, bp 1DAD0B54, ip 3, JadeSessionManager(SessionManager)>>unhandledException:}
	receiver: a JadeSessionManager
	arg[0]: a BoundsError

{1DAD0B38: cf 1DAD0B19, sp 1DAD0B4C, bp 1DAD0B34, ip 3, JadeSessionManager(SessionManager)>>onUnhandledError:}
	receiver: a JadeSessionManager
	arg[0]: a BoundsError

{1DAD0B18: cf 1DAD0AFD, sp 1DAD0B2C, bp 1DAD0B18, ip 5, BoundsError(Error)>>defaultAction}
	receiver: a BoundsError

{1DAD0AFC: cf 1DAD0AC9, sp 1DAD0B10, bp 1DAD0AE4, ip 55, BoundsError(Exception)>>_propagateFrom:}
	receiver: a BoundsError
	arg[0]: a ExceptionHandler
	stack temp[0]: nil
	stack temp[1]: a ExceptionHandler
	stack temp[2]: nil
	stack temp[3]: a Process('Main' base 1DAD0000 [ACTIVE] in SessionManager>>logError: sp=00000000 ip=4 list=025C0010)
	stack temp[4]: nil

{1DAD0AC8: cf 1DAD0AA9, sp 1DAD0ADC, bp 1DAD0AC4, ip 6, BoundsError(Exception)>>_propagate}
	receiver: a BoundsError
	stack temp[0]: nil

{1DAD0AA8: cf 1DAD0A8D, sp 1DAD0ABC, bp 1DAD0AA8, ip 13, BoundsError(Exception)>>signal}
	receiver: a BoundsError

{1DAD0A8C: cf 1DAD0A69, sp 1DAD0AA0, bp 1DAD0A84, ip 8, BoundsError(Exception)>>signal:with:}
	receiver: a BoundsError
	arg[0]: nil
	arg[1]: 5

{1DAD0A68: cf 1DAD0A49, sp 1DAD0A7C, bp 1DAD0A64, ip 5, BoundsError(Exception)>>signalWith:}
	receiver: a BoundsError
	arg[0]: 5

{1DAD0A48: cf 1DAD0A29, sp 1DAD0A5C, bp 1DAD0A44, ip 8, Array(Object)>>errorSubscriptBounds:}
	receiver: a Array
	arg[0]: 5

{1DAD0A28: cf 1DAD0A09, sp 1DAD0A3C, bp 1DAD0A24, ip 9, Array(Object)>>errorAt:}
	receiver: a Array
	arg[0]: 5

{1DAD0A08: cf 1DAD09E9, sp 1DAD0A1C, bp 1DAD0A04, ip 3, Array(ArrayedCollection)>>at:}
	receiver: a Array
	arg[0]: 5

{1DAD09E8: cf 1DAD09BD, sp 1DAD09FC, bp 1DAD09D8, ip 5, MethodSourcePresenter>>showStepPoint:}
	receiver: a MethodSourcePresenter
	arg[0]: 5
	stack temp[0]: nil
	stack temp[1]: nil
	stack temp[2]: nil

{1DAD09BC: cf 1DAD0995, sp 1DAD09D0, bp 1DAD09B0, ip 123, RowanDebugger>>selectedFrame}
	receiver: a RowanDebugger
	stack temp[0]: 9
	stack temp[1]: a Array
	stack temp[2]: 'moveNewClassVersionInSystem: aClassMove\0A\\0A\\09\"Move the class association for the cl...'

{1DAD0994: cf 1DAD0979, sp 1DAD09A8, bp 1DAD0994, ip 9, [] in RowanDebugger(JadeDebugger)>>selectedFrameWithErrorHandling}
	receiver: a RowanDebugger

{1DAD0978: cf 1DAD095D, sp 1DAD098C, bp 1DAD0978, ip 13, ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry}
	receiver: a ExceptionHandler

{1DAD095C: cf 1DAD0935, sp 1DAD0970, bp 1DAD0958, ip 22, [] in ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler

{1DAD0934: cf 1DAD0915, sp 1DAD0948, bp 1DAD0930, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:

{1DAD0914: cf 1DAD08F1, sp 1DAD0928, bp 1DAD090C, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 17 in ExceptionHandlerAbstract>>try:
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:
	stack temp[0]: nil

{1DAD08F0: cf 1DAD08C9, sp 1DAD0904, bp 1DAD08E4, ip 44, ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler
	arg[0]: [] @ 8 in JadeDebugger>>selectedFrameWithErrorHandling
	stack temp[0]: a ExceptionHandler
	stack temp[1]: a Process('Main' base 1DAD0000 [ACTIVE] in SessionManager>>logError: sp=00000000 ip=4 list=025C0010)
	env temp[0]: nil

{1DAD08C8: cf 1DAD08A5, sp 1DAD08DC, bp 1DAD08C0, ip 7, BlockClosure>>on:do:}
	receiver: [] @ 8 in JadeDebugger>>selectedFrameWithErrorHandling
	arg[0]: RowanDebuggerStepPointError
	arg[1]: [] @ 14 in JadeDebugger>>selectedFrameWithErrorHandling

{1DAD08A4: cf 1DAD0889, sp 1DAD08B8, bp 1DAD08A4, ip 24, RowanDebugger(JadeDebugger)>>selectedFrameWithErrorHandling}
	receiver: a RowanDebugger

{1DAD0888: cf 1DAD0865, sp 1DAD089C, bp 1DAD0880, ip 13, EventMessageSend>>forwardTo:withArguments:}
	receiver: a EventMessageSend
	arg[0]: a RowanDebugger
	arg[1]: a Array

{1DAD0864: cf 1DAD0849, sp 1DAD0878, bp 1DAD0864, ip 5, EventMessageSend>>value}
	receiver: a EventMessageSend

{1DAD0848: cf 1DAD0821, sp 1DAD085C, bp 1DAD0844, ip 11, [] in MessageSequenceAbstract>>value}
	receiver: nil
	arg[0]: a EventMessageSend

{1DAD0820: cf 1DAD07F1, sp 1DAD083C, bp 1DAD080C, ip 30, EventMessageSequence>>messagesDo:}
	receiver: a EventMessageSequence
	arg[0]: [] @ 9 in MessageSequenceAbstract>>value
	stack temp[0]: a DeadObject
	stack temp[1]: 1
	stack temp[2]: a RowanDebugger
	stack temp[3]: a EventMessageSend

{1DAD07F0: cf 1DAD07D5, sp 1DAD0804, bp 1DAD07F0, ip 15, EventMessageSequence(MessageSequenceAbstract)>>value}
	receiver: a EventMessageSequence
	env temp[0]: nil

{1DAD07D4: cf 1DAD07B5, sp 1DAD07E8, bp 1DAD07D0, ip 8, EventsCollection>>triggerEvent:}
	receiver: a EventsCollection
	arg[0]: selectionChanged

{1DAD07B4: cf 1DAD0795, sp 1DAD07C8, bp 1DAD07B0, ip 4, ListPresenter(Object)>>trigger:}
	receiver: a ListPresenter
	arg[0]: selectionChanged

{1DAD0794: cf 1DAD0779, sp 1DAD07A8, bp 1DAD0794, ip 4, ListBox(ListControlView)>>onSelectionChanged}
	receiver: a ListBox

{1DAD0778: cf 1DAD075D, sp 1DAD078C, bp 1DAD0778, ip 3, ListPresenter(SelectableItemsPresenter)>>onSelectionChanged}
	receiver: a ListPresenter

{1DAD075C: cf 1DAD073D, sp 1DAD0770, bp 1DAD0758, ip 6, ListBox(ListControlView)>>onSelChanged:}
	receiver: a ListBox
	arg[0]: a Array

{1DAD073C: cf 1DAD071D, sp 1DAD0750, bp 1DAD0738, ip 7, ListBox(BasicListAbstract)>>onSelChanged:}
	receiver: a ListBox
	arg[0]: a Array

{1DAD071C: cf 1DAD06FD, sp 1DAD0730, bp 1DAD0718, ip 24, ListBox(BasicListAbstract)>>onSelChanging}
	receiver: a ListBox
	stack temp[0]: a Array

{1DAD06FC: cf 1DAD06E1, sp 1DAD0710, bp 1DAD06FC, ip 2, ListBox>>lbnSelChange}
	receiver: a ListBox

{1DAD06E0: cf 1DAD06B9, sp 1DAD06F4, bp 1DAD06D4, ip 10, ListBox>>command:id:}
	receiver: a ListBox
	arg[0]: 1
	arg[1]: 12991
	stack temp[0]: lbnSelChange

{1DAD06B8: cf 1DAD0685, sp 1DAD06CC, bp 1DAD06A0, ip 35, ContainerView(View)>>wmCommand:wParam:lParam:}
	receiver: a ContainerView
	arg[0]: 273
	arg[1]: 78527
	arg[2]: 1180782
	stack temp[0]: 12991
	stack temp[1]: nil
	stack temp[2]: a ListBox

{1DAD0684: cf 1DAD0655, sp 1DAD0698, bp 1DAD0670, ip 23, ContainerView(View)>>dispatchMessage:wParam:lParam:}
	receiver: a ContainerView
	arg[0]: 273
	arg[1]: 78527
	arg[2]: 1180782
	stack temp[0]: nil
	stack temp[1]: wmCommand:wParam:lParam:

{1DAD0654: cf 1DAD0621, sp 1DAD0668, bp 1DAD0644, ip 69, [] in InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: nil

{1DAD0620: cf 1DAD05F9, sp 1DAD0634, bp 1DAD061C, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 79 in InputState>>wndProc:message:wParam:lParam:cookie:

{1DAD05F8: cf 1DAD05AD, sp 1DAD0614, bp 1DAD05E0, ip 84, InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: a InputState
	arg[0]: 1574678
	arg[1]: 273
	arg[2]: 78527
	arg[3]: 1180782
	arg[4]: 850552
	stack temp[0]: a ContainerView

{1DAD05AC: cf 1DAD0585, sp 1DAD05D8, bp 1DAD05A0, ip 10, ListBox(ControlView)>>defaultWindowProcessing:wParam:lParam:}
	receiver: a ListBox
	arg[0]: 514
	arg[1]: 0
	arg[2]: 6619448

{1DAD0584: cf 1DAD0569, sp 1DAD0598, bp 1DAD0584, ip 12, MouseEvent(WindowsEvent)>>defaultWindowProcessing}
	receiver: a MouseEvent

{1DAD0568: cf 1DAD0549, sp 1DAD057C, bp 1DAD0564, ip 8, ListBox(View)>>onLeftButtonReleased:}
	receiver: a ListBox
	arg[0]: a MouseEvent

{1DAD0548: cf 1DAD0529, sp 1DAD055C, bp 1DAD0544, ip 4, ListPresenter(Presenter)>>onLeftButtonReleased:}
	receiver: a ListPresenter
	arg[0]: a MouseEvent

{1DAD0528: cf 1DAD0501, sp 1DAD053C, bp 1DAD051C, ip 9, ListBox(View)>>wmLButtonUp:wParam:lParam:}
	receiver: a ListBox
	arg[0]: 514
	arg[1]: 0
	arg[2]: 6619448

{1DAD0500: cf 1DAD04D1, sp 1DAD0514, bp 1DAD04EC, ip 23, ListBox(View)>>dispatchMessage:wParam:lParam:}
	receiver: a ListBox
	arg[0]: 514
	arg[1]: 0
	arg[2]: 6619448
	stack temp[0]: nil
	stack temp[1]: wmLButtonUp:wParam:lParam:

{1DAD04D0: cf 1DAD049D, sp 1DAD04E4, bp 1DAD04C0, ip 69, [] in InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: nil

{1DAD049C: cf 1DAD0475, sp 1DAD04B0, bp 1DAD0498, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 79 in InputState>>wndProc:message:wParam:lParam:cookie:

{1DAD0474: cf 1DAD0435, sp 1DAD0490, bp 1DAD045C, ip 84, InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: a InputState
	arg[0]: 1180782
	arg[1]: 514
	arg[2]: 0
	arg[3]: 6619448
	arg[4]: 851240
	stack temp[0]: a ListBox

{1DAD0434: cf 1DAD0415, sp 1DAD0454, bp 1DAD0430, ip 6, ShellView(View)>>isDialogMessage:}
	receiver: a ShellView
	arg[0]: a MSG

{1DAD0414: cf 1DAD03F5, sp 1DAD0428, bp 1DAD0410, ip 5, ShellView>>preTranslateMouseInput:}
	receiver: a ShellView
	arg[0]: a MSG

{1DAD03F4: cf 1DAD03D5, sp 1DAD0408, bp 1DAD03F0, ip 13, ShellView(View)>>preTranslateMessage:}
	receiver: a ShellView
	arg[0]: a MSG

{1DAD03D4: cf 1DAD03AD, sp 1DAD03E8, bp 1DAD03C8, ip 17, InputState>>preTranslateMessage:}
	receiver: a InputState
	arg[0]: a MSG
	stack temp[0]: 1442828
	stack temp[1]: a ShellView

{1DAD03AC: cf 1DAD038D, sp 1DAD03C0, bp 1DAD03A8, ip 19, InputState>>pumpMessage:}
	receiver: a InputState
	arg[0]: a MSG

{1DAD038C: cf 1DAD0361, sp 1DAD03A0, bp 1DAD037C, ip 18, InputState>>loopWhile:}
	receiver: a InputState
	arg[0]: [] @ 9 in InputState>>mainLoop
	stack temp[0]: a MSG
	stack temp[1]: true
	stack temp[2]: nil

{1DAD0360: cf 1DAD0345, sp 1DAD0374, bp 1DAD0360, ip 15, InputState>>mainLoop}
	receiver: a InputState

{1DAD0344: cf 1DAD0329, sp 1DAD0358, bp 1DAD0344, ip 14, [] in InputState>>forkMain}
	receiver: a InputState

{1DAD0328: cf 1DAD030D, sp 1DAD033C, bp 1DAD0328, ip 13, ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry}
	receiver: a ExceptionHandler

{1DAD030C: cf 1DAD02E5, sp 1DAD0320, bp 1DAD0308, ip 22, [] in ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler

{1DAD02E4: cf 1DAD02C5, sp 1DAD02F8, bp 1DAD02E0, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:

{1DAD02C4: cf 1DAD02A1, sp 1DAD02D8, bp 1DAD02BC, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 17 in ExceptionHandlerAbstract>>try:
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:
	stack temp[0]: nil

{1DAD02A0: cf 1DAD0279, sp 1DAD02B4, bp 1DAD0294, ip 44, ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler
	arg[0]: [] @ 10 in InputState>>forkMain
	stack temp[0]: nil
	stack temp[1]: a Process('Main' base 1DAD0000 [ACTIVE] in SessionManager>>logError: sp=00000000 ip=4 list=025C0010)
	env temp[0]: nil

{1DAD0278: cf 1DAD0255, sp 1DAD028C, bp 1DAD0270, ip 7, BlockClosure>>on:do:}
	receiver: [] @ 10 in InputState>>forkMain
	arg[0]: ProcessTermination
	arg[1]: [] @ 13 in BlockClosure>>newProcess

{1DAD0254: cf 00000001, sp 1DAD0268, bp 1DAD0254, ip 17, [] in BlockClosure>>newProcess}
	receiver: [] @ 10 in InputState>>forkMain

<Bottom of stack>

***** End of dump *****

***** Ending Dolphin stack dump started at 4:43:28 PM 12/14/2018 *****
```
Not sure how reproducable this is ... but I was trying to reproduce a bug for which I have two scripts to create the walkback ... haven't rerun scripts, yet to see if it does reproduce ...

**Comment by dalehenrich** [comment] 2018-12-15 01:31
Bringing up the debugger on rerun of the code that produced the original error, did produce a similar debugger stack, but clicking around in the debugger does not reproduce the bug ... from the screen shot, I can see that there is a project browser open and an inspector .... I was in the midst of trying to understand the error when the debugger blew up on me ... so it seems that there were some harmful side effects of some operations I was performing ... hopefully the dolphin stack will be informative.

**Comment by dalehenrich** [comment] 2018-12-15 01:36
heh heh, it looks I was able to force the error again ... here's the screen shot of the error:
![image](https://user-images.githubusercontent.com/623951/50037460-576a6c80-ffc6-11e8-8081-418d335c7cc0.png)
Bringing up the following menu item seems to cause the `index out of bounds error`:
![image](https://user-images.githubusercontent.com/623951/50037479-854fb100-ffc6-11e8-983a-68f0862ffcaf.png)
I wanted to see the implementors of `addNewClassVersionToAssociation:instance:` but as you can see the menu did not give me a choice of implementors/senders ... which is yet another bug ... turns out the debugger was as upset about the missing  implementors/senders as I was:)

**Comment by dalehenrich** [comment] 2018-12-15 01:39
Seems that none of the of the frames are giving me senders/implementers:
![image](https://user-images.githubusercontent.com/623951/50037511-04dd8000-ffc7-11e8-94aa-7a0cce070c4c.png)

**Comment by ericwinger** [comment] 2018-12-18 22:18
I don't have a reproduction case but Oscar 3.0.53 will have a fix for a similar bug I was able to reproduce. There was a path through method update where a method was getting marked as deleted when it shouldn't have been.

**Comment by dalehenrich** [comment] 2018-12-20 00:07
reappeared in 3.0.53:
![image](https://user-images.githubusercontent.com/623951/50255768-20220400-03a8-11e9-8391-546b6a7e8a5f.png)

**Comment by ericwinger** [comment] 2018-12-29 19:51
The stack shows that the frame's stepPoint is erroneously set to 5. Looking at the [picture](https://github.com/GemTalk/Jadeite/issues/362#issuecomment-448799006), there appear to only be 4 step points in the method. 

The stepPoint is set on the server ``RowanFrameService>>initializeProcess:level:organizer:`` and not modified on the client. The relevant part of the method is here:
```
...
	stepPoint := gsNMethod == gsNMethod homeMethod
		ifTrue: [aGsProcess _stepPointAt: anInteger]
		ifFalse: [gsNMethod homeMethod _stepPointForMeth: gsNMethod ip: (frameData at: 2)].
...
```

Assuming that 1) there isn't another step point hiding under the dialog in the picture and that 2) step points is correctly set to 4, I'm going to need a reproduction case to debug. Assigning to @dalehenrich and @LisaAlmarode for reproduction case. 

Without a reproduction case, I would need to resolve issue #349 and build call tracing into Jadeite to see what the frame service inst var values are coming back from the server.

**Comment by ericwinger** [comment] 2018-12-31 18:17
@LisaAlmarode In talking with Dale, he said that this type of bug sometimes happens when he has opened a debugger but then is doing other work (say) in the project browser and doing lots of aborts. It's possible that a reproduction case might be found with  this in mind.

**Comment by LisaAlmarode** [comment] 2019-08-15 19:52
Closing since it's been so long.  Dale, reopen if you see it again.

**Closed as completed by LisaAlmarode** 2019-08-15 19:52 UTC
Labels: bug, P1-critical
