### ISSUE TITLE
Commit to git failure.

### ISSUE THREAD

**Issue by alexkogan** [ericwinger/Jade#469] opened 2019-05-06 21:43 UTC
Commit to git relies on single tmp file for commit message. If another user has already created such file and left it behind it prevents other users from committing on same server.
Also code need to check if GsFile open... returned nil and report an error possibly. 
![image](https://user-images.githubusercontent.com/1958382/57257075-38b85100-700d-11e9-9bff-521d514526b9.png)

**Comment by ericwinger** [comment] 2019-05-13 16:14
@dalehenrich Should this be a rowan issue?

**Comment by dalehenrich** [comment] 2019-05-13 16:20
Yes ... and this is a duplicate of GemTalk/Rowan#257

**Closed as completed by dalehenrich** 2019-05-13 16:20 UTC
