### ISSUE TITLE
Breakpoint within a block is only honored for a few iterations 

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#884] opened 2021-09-16 18:52 UTC
If you set a breakpoint within a block, you expect it to trip each time the block executes.  It seems to stop after 1-3 iterations of the loop.  The code run fine; it just decides it doesn't want to bother stopping any more. 

This is with 3.7 private build of Dale's from Sept 1, Rowan CandidateV3.0 fd2e276c8, Oscar 3.2pre-release3.  It appears to happen in the .exe but not in development of Jadeite, and Eric did reproduce it on his earlier Rowan in the exe. Current signs are that it's a Jadeite issue. 

... this bug makes debugging very difficult... I noticed a product bug in Plantis, so this was a real-life test.  However, Eric asked about step out, and using step out does let me iterate and stops at my breakpoint every time.

**Comment by ericwinger** [comment] 2021-09-16 19:25
I was able to reproduce it one time using `Jadeite.exe`. Was unable to reproduce at all in development environment and (so far) no further using the .exe.

**Comment by LisaAlmarode** [comment] 2022-11-16 20:45
The behavior is quite odd in 3.2.12, and not in a good way.  

This is my test method:
```
blockIteration
"ThreeTest new blockIteration"

  | clsOrg report res |
  clsOrg := ClassOrganizer newExcludingGlobals.
  report := { #'flattened' . #'pairsCollect:' . #'containsDigit' . #'blarf' . #sunshine . #tuesday . #asString . #asInteger . #now} 
      select: [:sel |
          res := clsOrg implementorsOf: sel.
          res size > 0
          ].
  ^report
```

I put a breakpoint on size (step point 10).
Then do an Inspect on ThreeTest new blockIteration.  It stops on the breakpoint.

- [x] However, if I press the run icon, it continues and does exactly nothing more. I would have expected it to break in the next iteration; and if the meaning of run icon has changed, at least it should show me the results in an inspector.

- [x] If I inspect-it on the above code, and use step out, I have to hit step out twice per loop iteration, the breakpoint doesn't  re-trigger but that might be okay.  But if I continue to step past the time the code is finished, it never gets to a place where it returns the inspector results, and if I click too far into the infrastruture before I press run, I get this:
![image](https://user-images.githubusercontent.com/13142166/202289786-094b3298-9b5c-48ed-8048-c13d5c108792.png)

**Comment by ericwinger** [comment] 2022-12-08 23:06
1. If an attempt is made to open a debugger on an already debugged process, Jadeite is not supposed to open a new one. However, sometimes, Jadeite thought that a debugger being closed was actually still open so it stopped. That is fixed. 
2. When stepping out, we probably should not step into the framework code on the server. I *think* if a step out is attempted and if the method's home method is nil, we've reached the outer most context of our debugged code and should just resume.

**Comment by ericwinger** [comment] 2022-12-08 23:15
Didn't mean to close.

**Comment by ericwinger** [comment] 2022-12-10 00:11
Added some tests.

**Comment by ericwinger** [comment] 2022-12-12 17:54
Fixed in 3.2.14.

**Comment by LisaAlmarode** [comment] 2023-01-25 19:52
The second complaint with step out, now appears to work reliably.

However, the first example still better, but not yet fully functional. 

Using the above method,
- put a breakpoint on size (step point 10).
- do an Inspect on ThreeTest new blockIteration. It stops on the breakpoint.
- press run. it break in the next iteration
- continue to press run. it should stop the breakpoint in the next loop (loop should execute 9 times)
- after a variable number of run-break repeats, it says:

![image](https://user-images.githubusercontent.com/13142166/214673458-a26c57fc-8bf5-4366-9b81-6f2445ec381d.png)

And OK makes everything go away.  I should be able to actually get to an inspector.

**Comment by ericwinger** [comment] 2023-02-01 01:11
Possible fix - The session from a closing debugger was nil. When it tried to get it's process list, the service returned with nil for a process list and gave up.  Lisa will need to test as she has a better test case.

**Closed as completed by ericwinger** 2023-02-01 01:11 UTC
Labels: bug, P2-Significant, FixInFirstCut
