### ISSUE TITLE
Error on add subclass if that class is not not explicitly selected

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#334] opened 2018-11-27 21:47 UTC
In a package look at the list view of classes.  

Move the mouse over a class that is not selected - don't select it.   Right click to bring up the menu.  It highlights the new class as well as presents a menu.  If you select "add subclass" you get an error dialog:

BrowserUpdate does not understand #first

Other menu items seem to work.

**Comment by ericwinger** [comment] 2018-12-01 00:00
This is a tricky problem. With luck, my fix in 3.0.51 is solid. 

Essentially, the problem is that when we select a class, Jadeite goes to the server to refresh itself and pull back it's method list. With a left click, that works just fine. However when you right click and select at the same time, a dialog is raised. The menu dialog thread takes over Dolphin and doesn't allow the class refresh to finish (sometimes depending on event order). When Add Subclass is selected, it issues a server command to retrieve the class template. That finds the update still is in progress and gives up and walks back. 

The fix was not trivial. In order to avoid sending a class refresh and the add subclass command within the menu thread, I had to move the class refresh to a different event (``selectionChanged`` to ``selectionChanging:``). However, the ``selectionChanging:`` event is not (stupidly) sent except when a button is clicked. That meant tests will not see the ``selectionChanging:`` event. Therefore, I needed to register the class & hierarchy lists to receive both events and careful decide which event should take precedence. 

This bug could happen anytime a select is done with the right click and a menu option is invoked that calls the server. I've only fixed the immediate case so others may be lurking. Because the failure cases are often benign (a missed command that needs to be resent) there may not be as many gross errors as this one.

**Comment by LisaAlmarode** [comment] 2018-12-03 04:31
The bug itself does not reproduce.  However, if I make a drag operation (that is, press down right button and move) in the classes pane, I now get an error:
ListView does not understand #nmBeginRDrag:

**Comment by ericwinger** [comment] 2018-12-03 17:49
See #338.

**Comment by ericwinger** [comment] 2018-12-05 00:16
Pulling out my fix in 3.0.51. There were unexpected and difficult side effects.

**Comment by LisaAlmarode** [comment] 2018-12-10 17:48
in 3.0.52, in the class list hierarchy view (but not the class list view), a drag over a class that was not previously selected gets an error exactly one object must be selected.  A drag over a class that was selected gets a RowanClassService does not understand #last.  I couldn't find other problems with dragging.

It's odd that it's quite solid in the list view and so fragile in the hierarchy view.

**Comment by ericwinger** [comment] 2018-12-12 23:05
The hierarchy/class lists and events that I inherited in Jade are separate code paths. With this checkin (042dac9c) I made a tiny bit of progress simplifying them. 

I've got a fix in 3.0.53 for the drag bugs mentioned in this comment https://github.com/GemTalk/Jadeite/issues/334#issuecomment-445907219

**Comment by ericwinger** [comment] 2019-02-23 00:13
After running into a bug related to this, I was able to root around and find a better solution. Here's the chain of events that causes the problem. 

- User selects new class with right mouse. 
- Menu pops up blocking a class refresh. 
- User selects menu item (for me it was ``Browse References``) 
(At this point there are a couple server calls queued up)
- After menu item is selected, the class refresh proceeds
- After sending it's call to the gci it sent ``SessionManager inputState loopWhile:``  -- this was the real problem
- That noticed ``Browse References`` and tried to execute it
- Because the server was busy, ``Browse References`` failed - causing problems. 

The solution was to block the the refresh class so no inputs are processed. This is similar to the notion of blocking in GBS.  The refresh class blocks and doesn't let the browse references proceed until it's done. This not only solves the immediate problem but ``blockWhile:`` is available if this type of problem comes up again. 

Fixed in 3.0.64 https://github.com/GemTalk/Jadeite/commit/f8b002afb1adbdca953702cb0cb06ae185b1836a

**Closed as completed by ericwinger** 2019-02-23 00:13 UTC
Labels: P3-Annoyance
