### ISSUE TITLE
On error when Sunit debug of inherited test, walkback displays class confusion (new in 3.0.93-6)

### ISSUE THREAD

**Issue by LisaAlmarode** [ericwinger/Jade#731] opened 2020-02-26 18:46 UTC
I have an abstract test class (PlantisTester), with three subclasses that actually run tests. When I am running tests on one of the subclasses (PlantisLiteTester), and there's a test error, I get a walkback, as expected.

However, starting in this release, the walkback is for a reason:rtErrSubclassResponsibility... it seems to think it's running the test inherited from PlantisTester on the class PlantisTester, not on PlantisLiteTester as I was doing.  And it gets an error in setup.  So I never reach the actual error.

**Comment by LisaAlmarode** [comment] 2020-02-26 23:10
Setup classes:
```
TestCase rwSubclass: 'LisaTest'
```
with following methods:
```
test_error
	self zork.
	self assert: false
test_okay
	self zork.
	self assert: true
zork
	^self subclassResponsibility: 'not supposed to run this kind of zork'
```
And the subclass:
```
LisaTest rwSubclass: 'LisaSubTest'
```
with only one method
```
zork
	^true
```

Now go to the sunit tab for LisaSubTest  (note, the sunit browser is not broken with this bug)

test_okay works fine.
test_error shows an assert failure.
However, if you use the debug icon to figure out the assert, you get:

![image](https://user-images.githubusercontent.com/13142166/75396736-1ba98300-58aa-11ea-9a2a-1c6a78eb6943.png)

**Comment by ericwinger** [comment] 2020-02-26 23:45
recent changed exposed bug in sunit tab. Tester was running tests as their compiled class not the selected class.

Fixed in 3.0.93 pre-release7

**Comment by LisaAlmarode** [comment] 2020-03-02 06:17
I seem to remember that this was indeed fixed in pr7; but it looks very much like this was re-introduced in pr8.

**Comment by ericwinger** [comment] 2020-03-02 17:53
Regression was related to the work for #736, commit https://github.com/GemTalk/Jadeite/commit/bfed80ecbd766788339a8c8b3cdcfb61f74dcc61.

Test didn't catch the problem because of a setup error in the test.  `JadeiteProjectBrowserLowerTabsTestCase>>test_sunitRunTestAsSelectedSubclass`

**Closed as completed by ericwinger** 2020-03-02 17:53 UTC
Labels: bug

**Comment by LisaAlmarode** [comment] 2020-03-03 20:06
Looks good in pr9
